### ISSUE TITLE
How to turn off momentum scrolling and have any swipe go to next or previous slide? 

### ISSUE THREAD

**Issue by akardet** [davidcetinkaya/embla-carousel#107]
Is it possible to fix/lock any swipe to go to the next slide in the carousel as opposed to triggering momentum scrolling on quick swipes?

**Comment by davidcetinkaya** [comment]
Hello Sam (@akardet),

Thank you for your question. I think this is more or less a duplicate of issue #38. But a lot have happened since then. The library has changed and Embla Carousel now exposes its core engine for extensibility, so I’m going to try if this is achievable with the current state of Embla. I’ll let you know when I have tried this.

Are you using the Vanilla or React version of Embla Carousel?

Best,
David

**Comment by akardet** [comment]
Thanks for the reply and linking to that helpful issue. I understand the design choice, I was just curious if there was an option exposed so in one place I can have the carousel locked to swiping one slide at a time and keeping the easing transition and in another place have the momentum scrolling. 

I'm using the React version of Embla.

**Comment by davidcetinkaya** [comment]
Hi again Sam (@akardet),

There’s no option to achieve this, sorry. Are you still interested in achieving this by extending the carousel? In that case I’ll try and see if it’s doable and will setup a CodeSandbox. 

Best,
David

**Comment by akardet** [comment]
Ah no worries, I'll give it a shot on my own and reach out if I have any other questions. I'll go ahead and close. 

Thanks again David!

**Comment by davidcetinkaya** [comment]
All right Sam (@akardet), feel free to reach out if you have questions or need any assistance.

Kindly,
David

**Comment by davidcetinkaya** [comment]
Duplicate of #38.
