### ISSUE TITLE
scrollTo's scroll direction is inconsistent

### ISSUE THREAD

**Issue by jeiea** [davidcetinkaya/embla-carousel#109]
### what I tried

Applying `embla.scrollTo(1)` to the carousel having only two slides. (and `loop: true`)

[codesandbox demo](https://codesandbox.io/s/embla-carousel-loop-react-forked-hu2cc?file=/src/js/EmblaCarousel.js)

### what I expected

New slide should appear from the right side.

### what I got

New slide appears from the left side only the first time.
This doesn't occur with more than 3 elements.

**Comment by davidcetinkaya** [comment]
Hi @jeiea,

Thanks for the CodeSandbox and clear issue description.

When `loop: true`, the `scrollTo()` method looks for the closest way to the target slide (based on its current location) in order to prevent excessive scrolling. For example, if you have 30 slides and the carousel is settled at slide 1, I don't think it makes sense to scroll 29 slides to reach slide 30. Instead, Embla will scroll backwards only one slide to reach 30.

The reason why this doesn't happen with 3 slides or more is because there will always be a closest way to the target slide. But, when you only have 2 slides with loop activated a special case occurs. Because when the carousel is settled at slide 1, the distance to slide 2 whether it's backward or forward will be exactly the same. So before you start scrolling, there is no closest way to the next slide.

By default, the `scrollTo()` method will just pick the first direction in the list, which happens to be backward. In your CodeSandbox you're triggering `scrollTo()` a second time (before the carousel has finished scrolling after the first `scrollTo()`), so the closest way to the next slide from its current scroll location will be forward (hence why it seems like its behaving inconsistently) from that position. If you change your test case to trigger `scrollTo()` after the carousel has settled:

```js
useEffect(() => {
  if (!embla) return

  // Trigger first scroll
  embla.scrollTo(1)

  // Trigger scroll again 1 second after the carousel has settled
  embla.on('settle', () => {
    setTimeout(() => {
      if (embla.selectedScrollSnap() === 1) {
        embla.scrollTo(0)
      } else {
        embla.scrollTo(1)
      }
    }, 1000)
  })
}, [embla])
```

You'll see that it actually behaves consistently. And maybe you're thinking that the first direction in the list should always be forward. Sure, that's easy to achieve. In that case adding this line [here](https://github.com/davidcetinkaya/embla-carousel/blob/master/src/vanilla/components/scrollTarget.ts#L30): 

```ts
function minDistance(d1: number, d2: number): number {
  if (Math.abs(d1) === Math.abs(d2)) return Math.min(d1, d2) // This line will make that happen
  return Math.abs(d1) < Math.abs(d2) ? d1 : d2
}
```

...will probably make it behave like you expect. But I don't think this is an issue because triggering the scroll doesn't break any functionality and scrolls the carousel to its target. Feel free to submit a PR if this is important to you, but please also make sure you test the solution properly before doing so.

If you just want to control the direction using `scrollTo()`, there is an undocumented feature of the method which is used internally, and forces the carousel towards a specific direction. `scrollTo()` accepts a second parameter which is the scroll **direction**:

- `0` or `undefined`, the carousel will decide the direction by finding the closest way to its target. 
- `-1` scrolls forward.
- `1` scrolls backward.

You may ask: Why does `-1` scroll forward? Because if the carousel is horizontal, a negative `transform: translate` will move the carousel forward (to the left to be specific).

I hope this helps.

Best,
David

**Comment by jeiea** [comment]
It's not very important to me. If consensus is necessary to decide what behaviour should be default, undocumented feature is sufficient to me.
Just for curiosity, if this is happening due to not settled state and seeking shortest distance, then shouldn't the scroll direction be LRLR(←→←→), instead of LRRR? My codesandbox did not settle in the middle, then scroll did not completely go through the slide, it would be shorter to go back.

**Comment by davidcetinkaya** [comment]
Hello again @jeiea,

You’re right. It should be LRLR. Flipping the comparisons on [this line](https://github.com/davidcetinkaya/embla-carousel/blob/9b8d391cae304640f3f747b1cfbe70f45c325cd1/src/vanilla/components/scrollTarget.ts#L51) seems to do the trick but I haven’t had the time to figure out why yet. 

You’re welcome to dig further if you want to solve it and make a contribution.

As mentioned earlier I don’t think this breaks any functionality and it’s an edge case (only happens with 2 slides) so I’m not going to prioritize it among other things to do right now. I hope you understand my reasoning. With that said, I appreciate you taking time creating a clear issue demonstrating this.

Best,
David

**Comment by kb8228** [comment]
@davidcetinkaya I know this is closed, but I'm facing the same issue in a carousel with 31 slides. It just reverses direction for a while and then resumes scrolling RTL like it should. I was unable to pass -1 as a second parameter to scrollTo because the second parameter is supposed to be 'jump' now. My carousel starts autoplaying on load.
```  const autoplay = useCallback(() => {
    if (!embla) return;
    if (embla.canScrollNext()) {
      embla.scrollNext();
    } else {
      embla.scrollTo(0);
    }
  }, [embla]);```

**Comment by davidcetinkaya** [comment]
Hi @kb8228,

It’s unclear to me what issue you’re experiencing. Please provide a CodeSandbox that clearly demonstrates the issue.

The code you posted is intended to reverse direction when it reaches the last slide and scroll to the first slide, in order to scroll forward again. This should be the case for carousels with the loop option set to `false`.

Regarding the direction parameter, you can just pass false to the scrollTo jump parameter:

```js
embla.scrollTo(5, false -1)
```

Best,
David

**Comment by kb8228** [comment]
@davidcetinkaya thanks for your answer! It's a carousel on a loop. I'll try with the direction param and let you know if I still have an issue.

**Comment by davidcetinkaya** [comment]
Hello @kb8228,

If you have loop enabled, the `embla.scrollTo()` should not be called at all in [the code snippet you posted](https://github.com/davidcetinkaya/embla-carousel/issues/109#issuecomment-956955135), because `embla.canScrollNext()` should always return `true`.

Read more about it [here](https://www.embla-carousel.com/api/methods/#canscrollnext) in the docs.

Best
David

**Comment by kb8228** [comment]
@davidcetinkaya then I'm really puzzled why it would reverse direction. Let me try to pin down in which specific conditions that happens.

**Comment by kb8228** [comment]
@davidcetinkaya does scrollNext accept a second argument for direction?

**Comment by kb8228** [comment]
@davidcetinkaya here's a sandbox that shows this strange behavior: https://codesandbox.io/s/vigorous-feynman-bgdiz?file=/components/ImageCarousel.jsx

It takes a little while before it starts scrolling backwards. I really appreciate if you could take a look!

**Comment by davidcetinkaya** [comment]
Hello again @kb8228,

I think the way you've setup the utilities for your autoplay functionality are clashing. It seems like you want to achieve a **continuous autoplay ticker** that moves at a constant speed. This has been brought up before in the following issue:

- #114 

Please take a look at the **CodeSandbox** in [this comment](https://github.com/davidcetinkaya/embla-carousel/issues/114#issuecomment-720385830) and let me know if that's what you're trying to achieve. If yes, that CodeSandbox shows a more optimal way of doing it.

Best,
David

**Comment by kb8228** [comment]
@davidcetinkaya that's exactly what I was trying to achieve, thanks so much!

**Comment by PurviJha** [comment]
Hi in my project i am using 2.4.4 version is this -1 is available for that version?

**Comment by davidcetinkaya** [comment]
Hi @PurviJha,

Which package are you using? `embla-carousel` or `embla-carousel-react`? v2.4.4 is a highly outdated version. You're missing out on a lot of new features. v6.2.0 is the latest release.

Best,
David

**Comment by PurviJha** [comment]
I am using embla carousel

**Comment by thomas-ecrubox** [comment]
Hello @davidjerleke 
I have met same issue like @jeiea.
Please let me know the solution.
