### ISSUE TITLE
Add browser support to README

### ISSUE THREAD

**Issue by davidcetinkaya** [davidcetinkaya/embla-carousel#11]
A `browser support list` is missing. It should be added to the README ASAP.

Thanks @ehellman for reporting this!

**Comment by davidcetinkaya** [comment]
Added in release [v1.0.0](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v1.0.0).

**Comment by davidjerleke** [comment]
@chrisj-skinner yes it was, but it was also later removed because I realized that I don’t have the time to update it.

You can find a little vague information about what browsers Embla supports [here](https://www.embla-carousel.com/get-started/) in the docs (read first section). It says all modern browsers. More specifically, Embla supports any browser that supports all the following features:

- IntersectionObserver 
- ResizeObserver
- MutationObserver

Feel free to make a PR and update the docs if you want.
