### ISSUE TITLE
Fade Slider?

### ISSUE THREAD

**Issue by IRasseI** [davidcetinkaya/embla-carousel#112]
Can you add Fade Effect in embla-carousel ?

**Comment by davidcetinkaya** [comment]
Hello @IRasseI and thank you for your question. This feature has already been requested in issue #39 so I'm going to tag this as a duplicate.

The issue was resolved after I created a [CodeSandbox](https://codesandbox.io/s/embla-carousel-github-issue-39-sdkul) that demonstrates how to achieve a fade effect, mostly by tweaking some CSS. Here's the [issue resolution](https://github.com/davidcetinkaya/embla-carousel/issues/39#issuecomment-568881867) for further reading. Please continue the conversation in issue #39 if the [CodeSandbox](https://codesandbox.io/s/embla-carousel-github-issue-39-sdkul) doesn't meet your requirements and you have further questions.

Best,
David

**Comment by davidcetinkaya** [comment]
Duplicate of #39.

**Comment by davidjerleke** [comment]
Released in [`8.1.0`](https://github.com/davidjerleke/embla-carousel/releases/tag/v8.1.0).
