### ISSUE TITLE
Scroll one slide at a time

### ISSUE THREAD

**Issue by patrickhuang94** [davidcetinkaya/embla-carousel#121]
Hi David! Thank you for your work on `embla-carousel`, it's been a joy to use so far in my project :)

Is it possible to move one slide at a time when `slidesToScroll` is set to 2 or more? This is what I'm asking for, visualized:

Expected:
<img width="189" alt="Screen Shot 2020-11-20 at 5 09 53 PM" src="https://user-images.githubusercontent.com/6422092/99863477-3962fa80-2b53-11eb-967a-c5eda97e5892.png">

What's happening:
<img width="178" alt="Screen Shot 2020-11-20 at 5 12 11 PM" src="https://user-images.githubusercontent.com/6422092/99863559-8cd54880-2b53-11eb-8d3c-8ec8a5ed67da.png">

Sandbox: https://codesandbox.io/s/embla-carousel-default-react-forked-scfoz?file=/src/js/EmblaCarousel.js

**Comment by davidcetinkaya** [comment]
Hi Patrick (@patrickhuang94),

Thank you for your question. Based on your description and visualization, I think you're looking for the `align` option, rather than `slidesToScroll`.

The purpose of `slidesToScroll` is to **merge** slides into the given number and make them act as if it was a single slide. Let's take `slidesToScroll: 2` as an example:

<img width="400" alt="slidesToScroll" src="https://user-images.githubusercontent.com/11529148/99875094-37e61080-2bed-11eb-98e2-8179a015475b.png">

As you can see, Embla treats every 2 slides as if it was a single slide behind the scenes. In order to achieve what you want, the following needs to be done:

- Create a carousel and set slide widths to 50%.
- Add the **option** `align: 'start'` because we want the slides to align to the left edge of the viewport.
- Add the **option** `containScroll: 'trimSnaps` to trim any leading/trailing scroll space.

Take a look at this [CodeSandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-121-t3kmy) I created for you and let me know if it helps!

Best,
David

**Comment by patrickhuang94** [comment]
@davidcetinkaya this is exactly what I was looking for. Thank you for the breakdown!

**Comment by davidcetinkaya** [comment]
You’re welcome @patrickhuang94. Enjoy!
