### ISSUE TITLE
Repeat items if necessary to achieve infinite scroll

### ISSUE THREAD

**Issue by openscript** [davidcetinkaya/embla-carousel#124]
Hello everybody

Based on #114 I could implement a continuously running slider. When the slider is too wide or there are not enough items, to fill the whole width the slider becomes buggy.

I've created a Sandbox [here](https://codesandbox.io/s/embla-carousel-react-github-issue-114-forked-t0px4). Here is a little clip about, which shows the problem:

![Peek 2020-11-21 11-40](https://user-images.githubusercontent.com/1105080/99875257-631d2f80-2bee-11eb-8d6b-c96e7ce9066b.png)

If I fill the whole visible width with items it works fine. Would it be easy to implement a feature within embla, which at least fills the visible width? .. because even if it isn't buggy, I want to fill the whole width for a nice appearance.

Thank you in advance!

**Comment by davidcetinkaya** [comment]
Hello Robin (@openscript),

Thank you for your feature request. At the moment, Embla has a built-in functionality that falls back to `loop: false` if the slide content isn't sufficient to create the loop effect. I've chosen this approach instead of cloning items because cloning items can cause a lot of problems in certain cases.

I guess when setting up the ticker you requested (in issue #114), I re-created the internal carousel loop so it doesn't respect the fallback. So you'll have to add clones yourself. You can do this by checking if there are enough slides to loop like so:

```ts
embla.dangerouslyGetEngine().slideLooper.canLoop() // returns --> boolean
```

I hope this helps.

Kindly,
David

**Comment by openscript** [comment]
Hello David

Thank you so much for the quick response.

That's a great hint with `canLoop()`. Also your point about not too loop, when there aren't enough items is very valid.

After all, when I want to fill up the empty space with items, I need to know how wide all items are as well as the whole slider. With the possibility that the user resized the window it becomes quite complicated. 

I understand now, that this is tricky to implement within embla. I think I won't scroll if there aren't enough items as you suggested.

Thank you again! :)

Robin

**Comment by davidcetinkaya** [comment]
Hi Robin (@openscript),

Thanks a lot for understanding!

Kindly,
David
