### ISSUE TITLE
youtube slider

### ISSUE THREAD

**Issue by ramiwi** [davidcetinkaya/embla-carousel#129]
Is there an example for using embla as a youtube video slider?

**Comment by davidcetinkaya** [comment]
Hi @ramiwi,

Thank you for your question. No, not at the time of writing. But it should be easy to achieve because Embla Carousel doesn't care about what you put inside the slide elements? Have you tried it yourself?

Kindly,
David

**Comment by ramiwi** [comment]
Yes, its tricky to keep the aspect ratio right for youtube iframe slides. Actually not specific to Embla but I wondered if someone had already created an embla youtube slider.

**Comment by davidcetinkaya** [comment]
I see. Are you using the VanillaJS or ReactJS version?

Kindly,
David

**Comment by ramiwi** [comment]
Vanilla js

**Comment by davidcetinkaya** [comment]
Allright @ramiwi. I'll create a CodeSandbox that demonstrates this when I have time. Any other requirements you had in mind?

**Comment by ramiwi** [comment]
This will be great!
For other requirements. a video slider usually displays multiple slides, as in the CodeSandbox you created for issue #69 (https://codesandbox.io/s/bppew) and preferably keeps the video frame proportions without cropping its content.

**Comment by davidcetinkaya** [comment]
Hi @ramiwi,

Thank you for the additional details. This is what I came up with:

- [Demo](https://j4ib5.csb.app/)
- [CodeSandbox](https://codesandbox.io/s/embla-carousel-vanilla-github-issue-129-j4ib5) 

In order to maintain correct aspect ratio throughout different screen sizes, which is 16:9 for Youtube videos, I use the `padding-bottom`-hack. You can read more about in [this article](https://css-tricks.com/aspect-ratio-boxes/).

Note that I intentionally added `draggable: false` to the Embla options like so:

```ts
const embla = EmblaCarousel(viewPort, {
  align: "start",
  containScroll: "trimSnaps",
  draggable: false // here
});
```

The reason for this is that Youtube-Iframes will "hijack" pointer events and use them to trigger events related to their video players. So when you drag with your pointer inside an iframe Embla won't receive any events.
One way to solve this issue is to use preview images inside the slides together with a play icon instead of iframes. And when a user clicks on a slide, it triggers a modal with an iframe.

Let me know if it helps.

Kindly,
David

**Comment by ramiwi** [comment]
It works great, thanks!

**Comment by davidcetinkaya** [comment]
Glad to hear that @ramiwi. Yes, you can use any desired width for your slides by changing `min-width` 👍🏻.

Closing this issue as resolved. Enjoy 🎉
