### ISSUE TITLE
Blank space before last slide 

### ISSUE THREAD

**Issue by maiconrs95** [davidcetinkaya/embla-carousel#13]
when align is start, the last slide automatically adds a blank. Is there any way to lock the last slide on the edge of the container?

![blank-space](https://user-images.githubusercontent.com/19610095/60033854-c284b200-967f-11e9-9378-253b291d6fdb.png)

**Comment by davidcetinkaya** [comment]
Hello Maicon @maiconrs95,

Thank you for opening this issue 🙂!
This is not possible at the moment of writing. But maybe this should be a property for the `option` object like so:

```javascript
const options = { noExcessiveScroll: true }
const embla = EmblaCarousel(elementNode, options)
}
```

Also `align: 'end'` is affected by this since there can be blank space at the beginning of the carousel too. However, if `loop: true`, `noExcessiveScroll` should have no effect.

Is this the kind of feature you're asking for?

**Comment by davidcetinkaya** [comment]
Hello again @maiconrs95,
Have you had the chance to consider my suggestion?

Thank you in advance 👍!

**Comment by davidcetinkaya** [comment]
Closing this due to lack of response. Feel free to reopen the issue if you don’t think it’s resolved.

Thanks!

**Comment by maiconrs95** [comment]
@davidcetinkaya, 
thank you very much. Sorry for the delay to respond, but I was not following anything for a while.
Apparently it is working as proposed.
Thank you very much

**Comment by davidcetinkaya** [comment]
Hi Maicon @maiconrs95 

No worries, that's understandable. I hope I didn't stress you and I'm glad it's working as you expected 🙂! 

Thank you very much for opening this issue! Your idea lead to a new feature for Embla Carousel which I think is a great addition 👍.

If you're a `React`-person, be sure to check out the [Embla Carousel React](https://github.com/davidcetinkaya/embla-carousel-react) version. Here's a React [CodeSandbox](https://codesandbox.io/s/embla-carousel-react-znjzv) for it.

Cheers 👋!
David
