### ISSUE TITLE
Add Option for Image Title and Caption

### ISSUE THREAD

**Issue by RoyiAvital** [davidcetinkaya/embla-carousel#130]
Is there a way to add _Image Title_ and _Caption_ per slide?

Similar to Bootstrap Carousel:

![image](https://user-images.githubusercontent.com/7347975/102143105-21d61380-3e6c-11eb-9416-f960f0156e03.png)

**Comment by davidcetinkaya** [comment]
Hi @RoyiAvital,
Thank you for your question.

The vision for Embla Carousel is that it should be a lightweight bare bones carousel library. It doesn't aim to be a carousel with an exhaustive set of features covering all use cases. So it should basically solve the hardest technical challenges with building great carousels and do it good, and the rest should be up to the user.

**Considering this feature request**
Embla Carousel doesn't care about what you put inside your slides. You can basically put anything there. So I don't think it makes sense to add this feature because it's outside the scope of what Embla Carousel should be responsible for.

Best,
David
