### ISSUE TITLE
A way to figure out if a scroll is happening

### ISSUE THREAD

**Issue by Mattensor** [davidcetinkaya/embla-carousel#132]
Hey

Awesome library, Thank you!

I have slides which have click events associated with them, I'd like to only allow click events when scrolling is not in progress. Is there a way I can figure this out?

My current config is:
![image](https://user-images.githubusercontent.com/10224902/102684438-63d0d200-423d-11eb-9091-6ea44d05d0b9.png)

Thanks

**Comment by davidcetinkaya** [comment]
Hi @Mattensor,

Thank you for your question. Before I suggest a solution, I would like to know if you want to disallow clicks as soon as the carousel is scrolling? Or only when the pointer interaction is a drag move?

Kindly,
David

**Comment by Mattensor** [comment]
Hey @davidcetinkaya,

Thanks for getting back to me so quick! 

Ideally I'd like a combination of both. 
When I drag and release (init a scroll) the element below receives the click event. I expect this would be the drag event I'd like to prevent. When scrolling elements are also clickable in the carousel, I'd also like to disallow this too. 

Appreciate your help,
Matt

**Comment by davidcetinkaya** [comment]
Hi @Mattensor,

Thank you for the additional details. I think you're looking for the Embla opt-in method named `embla.clickAllowed()`. I don't know if you're using the VanillaJS or ReactJS version of Embla. Anyhow, example usage for `embla.clickAllowed()` looks something along these lines:

#### VanillaJS

```ts
const onSlideClick = (index) => {
  if (!embla.clickAllowed()) return
  
  // Embla says the pointer interaction was a static click, and not a drag move.
  // Do your magic here...
}
```

```ts
embla.slideNodes().forEach((slide, index) => {
  slide.addEventListener('click', () => onSlideClick(index), false)
})
```

#### ReactJS

```tsx
const onSlideClick = useCallback((index) => {
  if (!embla || !embla.clickAllowed()) return

  // Embla says the pointer interaction was a static click, and not a drag move.
  // Do your magic here...
}, [embla])
```

```jsx
<div className="embla__container">
  {slides.map((slide, index) => {
    <div className="embla__slide" onClick={() => onSlideClick(index)}>
      ...
    </div>
  })}
</div>
```

#### How it works under the hood
If the pointer is **touch**, Embla will:
- Prevent a click when the gesture is a drag move.
- Prevent clicks when the carousel is clicked during scroll.

If the pointer is **mouse**, Embla will:
- Prevent a click when the gesture is a drag move.
- Not prevent clicks when the carousel is clicked during scroll.

The reason behind this design choice is that touch pointers scroll the document. And when the document is natively scrolling on touch devices, it prevents clicks until the user stops the scrolling and clicks again when its settled.

But mouse pointers are not used to scroll the document, unless you're dragging the scrollbar. And if you're dragging the scroll bar, it will prevent you from accidentally clicking anything on the webpage anyway, because the pointer is within the scroll bar area. So the assumption here is that we can be more certain that a click with a mouse pointer is intentional.

I hope my explanation makes sense.
Do you still want to prevent clicks when the carousel is clicked during scroll for mouse pointers? In that case I'll look into it.

Best,
David

**Comment by Mattensor** [comment]
Thanks David!

Thats was a great explanation, fixed my main issue. Don't worry about the looking into how to prevent clicks while the carousel is in scroll, the clickAllowed on drag event is more than enough. 

Here's my solution in react

### Parent Component
![image](https://user-images.githubusercontent.com/10224902/102701095-4e4cbe00-42b8-11eb-8abf-3d7ff4dc3a69.png)

Child Component
![image](https://user-images.githubusercontent.com/10224902/102701105-6a505f80-42b8-11eb-86b6-3e35f21cccb1.png)

**Comment by davidcetinkaya** [comment]
Nicely done! Thank you for sharing your code. It might help others wanting to achieve the same thing.

Enjoy 🙂.
