### ISSUE TITLE
Free drag carousel with variable width and wide slides

### ISSUE THREAD

**Issue by O4epegb** [davidcetinkaya/embla-carousel#135]
Hi David and everyone! First of all, Embla is awesome, great job, thank you!

I think I found some weird behaviour with free drag carousel with wide slides (wide as wider than viewport, and with variable width, but it probably also happens with fixed width, not sure)

So here is codesandbox, I forked "Variable width" example and changed css a little bit. Basically right now images fit to fixed 220px height and they can be any width.

https://3h2iv.csb.app/

If your screen is wider than first or last slide then everything is working fine

If you try 375px screen for example, then last slide will be 413px (423px with padding), and you won't be able to drag it to the end, some part of the slide will be hidden.

<img width="1174" alt="Screenshot 2021-01-06 at 13 10 48" src="https://user-images.githubusercontent.com/12836237/103756659-c4735380-5020-11eb-8545-e985367ba21b.png">

Same thing with first slide, it is wider than viewport then carousel will be already scrolled by default like that `transform: translate3d(-11.31%, 0px, 0px);` and left part of the first slide will be hidden from view.

I've tried different things, thought maybe it is problem with my css, but could not find a solution.

**Comment by davidcetinkaya** [comment]
Hi Danila (@O4epegb),
Thank you. I hope you're enjoying the library so far.

Thank you for your clear description and sandbox. I'm trying to recall if I considered supporting slides wider that than the viewport, when I was building the Embla core. And I think I didn't. If you don't mind me asking, what's the use case for slides wider than the viewport? Because the user won't be able to se the full slide at any given scroll position?

Kindly,
David

**Comment by O4epegb** [comment]
Well, it is not a direct use case, more like side effect from using original image width/height ratio (only constraining it by height). This is why I use free drag too (which is awesome), otherwise it would be quite weird indeed.

So if we show some wide image like 1000x600px (width-height), and the carousel have max-height of 200px, then image will be 333x200px and would not fit fully inside 320px screen (and 13px extra pixel would not fit inside carousel too and will be invisible, if it is first or last slide).

And if we try to limit images by viewport width (and preserve ration at the same time), then image like that will be smaller than other images (less than 200px height), with free space around it (to preserve ratio)

<img width="388" alt="Screenshot 2021-01-08 at 16 37 05" src="https://user-images.githubusercontent.com/12836237/104021434-ce878480-51cf-11eb-80de-67719becc2dd.png">

Hope that makes sense what I am trying to say :)

It is not like mandatory thing for me, it's quite rare case, but still, seems like if you are using free drag then it should be possible to have slides with any width. Like maybe someone want to show really long panorama image or something like that.

**Comment by davidcetinkaya** [comment]
Hi again Danila (@O4epegb),
Thank you for the additional explanation 🙂.

I think implementing this wouldn't be too hard, but it comes with a consequence that could confuse users. Embla has a method called `embla.slidesInView()` that retrieves all visible slides within the carousel viewport. Users can control how much of a slide that should be visible in order for it to be considered in view with the `inViewThreshold` option. It basically looks like this:

```ts
const options = { inViewThreshold: 1 };
const embla = EmblaCarousel(emblaNode, options);

console.log(embla.slidesInView());
```

This is what the documentation says about `inViewThreshold`:

> Choose a fraction representing the percentage portion of a slide that needs to be visible in order to be considered in view. 0.5 equals 50%.

So if a **slide is wider than the viewport** and the user chooses `1` for the `inViewThreshold` option, that slide will never be considered in view. Because the entire slide won't be visible at any scroll location. I don't know if this is an issue that's important to take into consideration or not, but it's one consequence that came to my mind when I was thinking about implementing this feature request.

Personally, when I think of carousels containing images with different aspect ratios, I mainly think of the red area in your screenshot as an expected side effect, except that most cases would have a black background or similar. Like this [lightbox carousel](https://sachinchoolur.github.io/lightgallery.js/) for example. Click on any of the images to start the carousel view:

<img width="600" alt="lightbox" src="https://user-images.githubusercontent.com/11529148/104106807-44ffb180-52b8-11eb-957c-13e48a8c66ef.png">

I don't know, maybe that's just me though 🙂. I'm going to call this a **feature request** because I didn't aim to support this when I build the Embla core. I can't promise anything, but I'll look into it a bit more when possible.

Kindly,
David

**Comment by O4epegb** [comment]
That's valid concern about slides in view, although since it will be rare case it might be acceptable to consider wider-than-viewport slides as visible if they take whole viewport by them self.

Well, like that, in minimal pseudocode :)

```
const isSlideInView = getVisiblePartOfSlide(slide) >= inViewThreshold
```

As for end result, blank space or fixed size slides does not really suit well for carousel when you mix vertical, landscape and square slides together, but if you preserve aspect ratios then it looks quite well, in my opinion!

I've made another example which is a little bit closer to what I have in real project:

https://5tkn2.csb.app/

(quite big pictures there, might take a while until they load)

I am not sure how hard to implement this, but thank you anyway for taking it into consideration!
I might look into code myself, it looks very clean and understandable, but I am not quite good with those things by myself :)

**Comment by davidcetinkaya** [comment]
Hi Danila (@O4epegb), sorry for the delayed response. 

Thank you for your input. I think this suggestion of yours makes sense:

>  it might be acceptable to consider wider-than-viewport slides as visible if they take whole viewport by them self.

The example you shared looks nice so I definitely get what you mean. I guess you can solve it with `object-fit` to a certain extent, but that will of course cut a part of each image, in order for it to not overflow its container.

I'll look into this when I have the time to do so. In the meantime, you might want to check out the following:

- The new [documentation website](https://www.embla-carousel.com/).
- [Release v4.2.0](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.2.0).
- [Release v4.3.0](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.3.0). 

Cheers,
David
