### ISSUE TITLE
Shaky when changing slides when there are more then 32+ slides.

### ISSUE THREAD

**Issue by cajogit** [davidcetinkaya/embla-carousel#139]
Hey, I have a basic setup with infinitescroll. Once i have more then 32+ slides in the carousel the slide change is getting more and more slow and shaky. I think its due to many slides in the carousel. I tested it without infinitescroll aswell with static slides and the same thing is happening. I can provide a codesandbox if its necessary. 
Is there a way i can implement useIniteScroll backwards aswell with removing some slides from the slides array?

**Comment by davidcetinkaya** [comment]
Hi @cajogit,

Thank you for your question. Sounds strange. An Embla user wrote [this](https://www.reddit.com/r/reactjs/comments/i8kept/comment/g1bverj):

> I just wanna say thank you for making this! I use it for my app Solfej and it works like a charm. Easy to implement and the performance is lovely (using 200+ items at once )

I personally tried 150 items when testing the infinite scroll example before I finished the CodeSandbox and didn’t experience any issues.

I need a CodeSandbox with your setup in order to try reproducing what you’re experiencing. And it would be helpful if you could share what device and browser you’re using.

> Is there a way i can implement useIniteScroll backwards aswell with removing some slides from the slides array?

I think it’s possible but at the time of writing, the current infinite scroll example isn’t designed to handle that. Depending on how you want it to work, like if you want the transition when removing the slides to be fluid, or if you’re fine with a carousel reset that stops the carousel when in motion, the approach would be different.

Kindly,
David

**Comment by cajogit** [comment]
Thanks for your quick answer. 
I just tried to replicate it real quick with a basic example. Gonna provide a deeper example once i got time. 

[https://codesandbox.io/s/embla-carousel-slidestoscroll-react-forked-iuihx?file=/src/js/index.js](url)

If i open as brower page it already does the shaky thing. Tested on MacOs Chrome and firefox.

**Comment by davidcetinkaya** [comment]
Hello again @cajogit,

That’s strange. I just tested it and it’s scrolling very smoothly. What do you mean by “shaky”? Like stuttering?

Kindly,
David

**Comment by cajogit** [comment]
Shuttering yeah

Im using a macbook pro 2012 and a imac 2015

**Comment by cajogit** [comment]
https://user-images.githubusercontent.com/77203523/106178205-c3ee5880-6199-11eb-8686-5c16b43b5a9b.mov

**Comment by davidcetinkaya** [comment]
Hi @cajogit,

You closed the issue. I'm curious, did you solve the stuttering you were experiencing?

Best,
David

**Comment by davidcetinkaya** [comment]
@cajogit?
