### ISSUE TITLE
Slide reset issue

### ISSUE THREAD

**Issue by callumbooth** [davidcetinkaya/embla-carousel#140]
Hi,

I'm not sure if this is a bug or not, but there is a weird interaction when rendering the same carousel conditionally in two places.

It might be easier to show than to explain so I've created a repro here: https://codesandbox.io/s/embla-carousel-reinit-issue-fgw2d?file=/src/js/EmblaCarousel.js

## Steps to reproduce

1. Go to the repro
2. Drag the carousel to go to slide 2.
3. Click on the "swap" button
4. See that the carousel has swapped back to slide 1.

Now if you remove the div on line 49 changing: `<div>{renderCarousel()}</div>` to just `{renderCarousel()}` then do the same steps as above, the carousel wont reset back to 0.

I know I can get around this by ensuring that the emblaRef is only ever used once but it popped up in a use case where it is cleaner to have a boolean higher and render the same carousel in two places.

Happy to give me info as required.

**Comment by davidcetinkaya** [comment]
Hi Callum (@callumbooth),

Thank you for the sandbox and the clear description of the issue.
Embla Carousel will mount from scratch and forget the current index if one of these 2 things change:

- The `viewportRef`.
- The `options` object.

While I was debugging, I noticed that `options` doesn't change in your example, but the `viewportRef` does.

> Now if you remove the div on line 49 changing: <div>{renderCarousel()}</div> to just {renderCarousel()} then do the same > steps as above, the carousel wont reset back to 0.

I'm not 100% sure about this, but when you remove the `<div>`, it seems like React considers the returned value from `renderCarousel()` to be equal to the previous returned value before the `swap` button is pressed. Because the internal `useEffect()` [on this line](https://github.com/davidcetinkaya/embla-carousel/blob/23b9d8972ffd80418f8e0aadaad095f8f6470d7d/src/react/index.ts#L31) doesn't trigger any change.

I don't think this is a bug, because we want Embla to re-mount from scratch if the ref changes. You can read more about a use case and why we would want that in [this issue](https://github.com/davidcetinkaya/embla-carousel/issues/91). I hope it makes sense.

One way to solve this would be to track the index yourself, and make use of the `startIndex` option Embla has, like so:

```ts
embla.reInit({ startIndex: currentIndex });
```

Let me know if this helps!

Best,
David

**Comment by callumbooth** [comment]
Hi David,

Thanks for the fast response, yeah I wasn't convinced when I created this issue that it was a "bug". 

I did try your solution of tracking the index and setting the start Index however that seems to have issues too.

Here is an updated repro based on the previous one. https://codesandbox.io/s/embla-carousel-reinit-issue-v2-oi56y?file=/src/js/EmblaCarousel.js

When using useState and dragging the animation gets skipped. Even when using useRef to avoid re renders when clicking swap there is an obvious flash.

Thanks

**Comment by davidcetinkaya** [comment]
Hi Callum (@callumbooth),

That's because you're setting the index as soon as the current slide changes, and passing the new options to the `useEmblaCarousel()` hook 🙂. As I mentioned in my [first comment](https://github.com/davidcetinkaya/embla-carousel/issues/140#issuecomment-772783112), the carousel will re-init from scratch and forget its current index when the **option** object passed to the `useEmblaCarousel()` hook changes.

> Embla Carousel will mount from scratch and forget the current index if one of these 2 things change:
> - The viewportRef.
> - The options object.

You should set it just before you toggle full screen. Please take a look at [this CodeSandbox](http://codesandbox.io/s/embla-carousel-reinit-issue-v2-forked-wwvc6?file=/src/js/EmblaCarousel.js) I created. There's still an issue though, there's a fast flash when you toggle to full screen. But this is expected if you unmount the carousel with a ternary, causing the `viewportRef` to change. If you're creating a full screen toggle, you can hide that with a transition though.

Let me know if you have additional questions!

Kindly,
David

**Comment by davidcetinkaya** [comment]
Hello Callum (@callumbooth),

I hope you don't mind me asking:

Have you considered adding a `ref` to the [fullscreen element](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen), and conditionally render elements that you only want to display when fullscreen is active, instead of using a ternary that un-mounts and mounts the carousel?

I'm thinking something along these lines:

```jsx
return (
  <div ref={fullscreenRef}>
    <Carousel />
    {fullscreenActive && <CarouselArrows />}
  </div>
);
```

Best,
David

**Comment by callumbooth** [comment]
Hi David,

I don't mind at all, always happy to look at different approaches. 

I ended up getting it working by ensuring that the carousel doesn't unmount (which was probably more efficient anyway) but the element.requestFullScreen looks really interesting so may see if it is worth refactoring at some point.

I'm going to close this since it never was a bug, I was just curious as to why it was happening which you have very helpfully answered and provided solutions to so thank you.

**Comment by davidcetinkaya** [comment]
Hi Callum (@callumbooth),

I’m glad you got it sorted.

Cheers!
David
