### ISSUE TITLE
Only works after a screen refresh (Vue framework)

### ISSUE THREAD

**Issue by xoumi** [davidcetinkaya/embla-carousel#16]
Embla only seems to work after the page is refreshed in some way such as a resize.
When the page loads at first, embla appears to be unresponsive, as if it does not exist.
I noticed the 'is-dragging' classes are being applied meaning embla is loaded and working but the transforms don't get applied until I resize the page.
In hindsight, it might be a vue issue, but I wanted to get your thoughts first before filing a vue issue.

**Comment by davidcetinkaya** [comment]
Hello @xoumi,
Thank you for opening this issue 👍.

It's a bit hard to troubleshoot without any code at hand, but I'm guessing that it has something to do with when:

```javascript
EmblaCarousel(elementNode, options);
```

...is called. Or similar 🤔.

Because front-end frameworks/libraries abstract the vanilla JavaScript away and often use **component methods**, like when a component has **mounted**. Maybe you need to hook on to a `mounted()` method or similar before initialising Embla? I don't think this is an issue related to Vue itself, but I may be wrong.

To make Embla compatible with React, I had to build a tiny [wrapper-component](https://github.com/davidcetinkaya/embla-carousel-react). This components utilises React component methods and enables React users to use Embla in their projects.

**Now I know you're using Vue**, so my point being is that we may need to build a Vue wrapper component to make Embla compatible with Vue. I'd be very happy if this issue leads to me being able to add a link to the Embla Carousel Vue package here 😃:

<img width="841" alt="Embla Carousel" src="https://user-images.githubusercontent.com/11529148/61858255-090b3d80-aec6-11e9-9bdd-cfdd463e818f.png">

Unfortunately I'm not so familiar with Vue so I'd be very happy if **someone could help me out** with this. Maybe the [Vue Flickity package](https://github.com/drewjbartlett/vue-flickity) code can be used as inspiration?

Does this make sense to you?

**Comment by xoumi** [comment]
Thanks for the quick reply !
And sorry for the late reply.
I'm just a beginner in the field of web development so I probably cannot go around writing generic use case modular wrappers but I can provide some insight on how it weirdly got fixed:
I went through the docs again and noticed the `position: relative` css on `embla__slide`.
Even though I've set the loop property of embla to false, I needed the `position: relative` to make it work.
Weird interaction I must say, plus the fact that it magically does work if the window is resized.

Anyhoo, I'll close the issue, good luck with getting a vue wrapper going, I'm sure many would benefit from it.

**Comment by davidcetinkaya** [comment]
Hi again @xoumi,

I've setup a working [CodeSandbox example](https://codesandbox.io/s/vue-template-1yoir) for you. It works on initialisation and doesn't need a resize in order to work correctly. 

Try it out if you like 👍!

Just a **disclaimer**: I write code in Vanilla JS and React on a daily basis so I don't feel comfy with Vue. I can't guarantee that the example I've setup for you follows any Vue best practices 😅.

**Comment by davidcetinkaya** [comment]
Building a Vue wrapper for Embla issue has been opened here #17.

**Comment by davidjerleke** [comment]
Hi @xoumi,

Just wanted to let you know that a Vue 3 Embla package is available now.

Read more [here](https://www.embla-carousel.com/get-started/vue/).

Cheers,
David

**Comment by vinisooo** [comment]
having the same issue on NextJS13. Adding `position: relative` to .`embla__slide` didn't work to me :(

**Comment by davidjerleke** [comment]
@vinisooo what version of Embla are you using?

**Comment by davidjerleke** [comment]
Hi @vinisooo,

That’s happening because transform scale alters element dimensions. And upon initialization, Embla has to read container and slide dimensions in order to calculate scroll positions correctly. If you want to apply scale on your slides you will have to wait until Embla has initialized.

Best,
David
