### ISSUE TITLE
onClick event being fired during drag

### ISSUE THREAD

**Issue by cliffordfajardo** [davidcetinkaya/embla-carousel#174]
### Bug is related to

- [ ] The Vanilla JavaScript version
- [ ] The React version
- [X] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Embla Carousel version
- 4.3.1 (older versions as well)

### Describe the bug
When dragging a slide and letting go, it triggers a `click` event when the drag is released. This can be problematic for carousel items that have click handlers on them.

A common thing people will do with carousel items is attach an `click` handler to trigger a specific behavior such as:
- opening a modal
- redirecting to another page in the app
- etc...

https://user-images.githubusercontent.com/6743796/113911974-77be2680-978f-11eb-9535-5a7731221cdf.mp4

### CodeSandbox
- https://codesandbox.io/s/embla-carousel-default-react-forked-ych4i?file=/src/js/EmblaCarousel.js

### Steps to reproduce
1. Add click handler on a carousel item
2. Drag the item and release

### Expected behavior
The api should be able to distinguish between a drag event and an on click event.

**Comment by davidcetinkaya** [comment]
Hi Clifford (@cliffordfajardo),

Thank you for your question. This is not a bug.

Have you read about the opt-in `clickAllowed` method in the [docs](https://www.embla-carousel.com/api/methods/#clickallowed)?

Maybe this [explanation](https://github.com/davidcetinkaya/embla-carousel/issues/132#issuecomment-748525600) from issue #132 which is related to this will help.

Let me know if it helps.

Best,
David

**Comment by cliffordfajardo** [comment]
Ahh nice - I missed that part of the docs 🤦 . I'll close this as I think this will resolve this my issue once I try it.

Randoms aside:
I can only imagine how busy you must be with this popular open source project. Have you heard or looked into at the free docs search Algolia provides for open source?
- https://www.algolia.com/for-open-source/
- https://docsearch.algolia.com/

It adds full text search for your docs? I feel like that could help minimize issues on your repo 😄 

A lot of the big popular libraries you mat have heard of use it ([webpack](https://webpack.js.org/loaders/file-loader/#root),  [react-query](https://react-query.tanstack.com/), [eslint](https://eslint.org/) ..etc)

**Comment by davidcetinkaya** [comment]
Hi Clifford (@cliffordfajardo),

Funny thing, I actually skimmed the Gatsby docs search section two days ago and they mention **Algolia**. But I assumed that I had to pay for it so I didn’t dig further, because I didn’t think it made sense to put all this spare time work into the library and start paying for running the docs too 😅.

Now that you mention the open source alternative they offer, I’ll definitely look into it. Thanks!

The documentation website is actually pretty new. I created it from scratch using GatsbyJs. 

The previous documentation website was pretty bad and something I hacked together in a day or so. I didn't have much time so I used Create React App and hard coded everything including the content, just to give Embla users something to start with.

But thanks to a some donations from some of my users, I was able to spend some real quality time with it. So I decided to improve both the visual looks and build a conventional documentation website. All content is written in Markdown which makes it really easy to edit and create new content.
I'm hoping to get more time soon to add more content under the Guides section, that shows users how to achieve specific goals.

And adding a search input to the docs is on my list, so thanks a lot for pointing me in this direction!

Best,
David

**Comment by davidcetinkaya** [comment]
Duplicate of #132.

**Comment by davidcetinkaya** [comment]
Hi @cliffordfajardo,

I recently released the search feature on the documentation website. I went with Algolia Docsearch.

Cheers,
David

**Comment by donghoon-song** [comment]
> Hi Clifford (@cliffordfajardo),
> 
> Thank you for your question. This is not a bug.
> 
> Have you read about the opt-in `clickAllowed` method in the [docs](https://www.embla-carousel.com/api/methods/#clickallowed)?
> 
> Maybe this [explanation](https://github.com/davidcetinkaya/embla-carousel/issues/132#issuecomment-748525600) from issue #132 which is related to this will help.
> 
> Let me know if it helps.
> 
> Best, David

@davidjerleke 
Hello. I can't find "clickAllowed" method in docs. Was it removed?

**Comment by davidjerleke** [comment]
@donghoon-song `clickAllowed` has been removed because it’s handled automatically now.

**Comment by nithiz** [comment]
@davidjerleke Just a little additional info on why a clickAllowed() function would still be useful. We're using product cards with a product variants slider. The whole product card is clickable. The slider handles clicks just fine, except when you're dragging and ending the drag outside of the slider (on the edge of the product card), a click still fires. We're still using a 7.x version now since we need that manual check and we can't upgrade because of this. 

Is there any chance a function or property will become available on the embla object to still check if clicking is allowed? Thanks!
