### ISSUE TITLE
Responsive slider item widths, `canScrollNext` not updating after resizing viewport

### ISSUE THREAD

**Issue by stianmartinsen** [davidcetinkaya/embla-carousel#196]
### Bug is related to

- [ ] The Vanilla JavaScript version
- [x] The React version
- [ ] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Embla Carousel version

- v4.5.3

### Describe the bug

When using Embla with responsive slider item widths, the previous/next buttons aren't disabled/enabled when the amount of visible slides change after a viewport resize.

### CodeSandbox

https://codesandbox.io/s/embla-carousel-arrows-dots-react-forked-773ht?file=/src/js/EmblaCarousel.js

### Steps to reproduce

1. Load the CodeSandbox with the preview window > 1024px wide.
2. See that there is only one "page" in the nav, and the next button is disabled.
3. Resize the preview window to < 1024px.
4. See error. The next button is still disabled, and I can't slide to the next page.

### Expected behavior

`canScrollPrev` and `canScrollNext` should give the correct result after the resize, disabling/enabling the buttons and slide functionality.

Any tips on how I could have the entire carousel update (toggling the disabled state on the previous/next buttons) when resizing the viewport would be greatly appreciated!

I really love this slider library btw! <3

**Comment by davidcetinkaya** [comment]
Hi @stianmartinsen,

Thank you for your bug report. I know this isn't super clear in the docs, but Embla won't re-initialize every time the window is resized. It will only re-initialize when the root element size changes (the one you attach the ref to). Here's the logic for this:

```js
function resize(): void {
  if (!activated) return
  const size = engine.axis.measureSize(sliderRoot.getBoundingClientRect())
  if (rootNodeSize !== size) reActivate() // This line does it
  events.emit('resize')
} 
```

The main reason for this is because we don't want vertical carousels to re-initialize and hard reset every time the window height changes on mobile devices. For example, on iPhones, the action bar at the bottom of the screen will appear and disappear depending on how you scroll. And this triggers a window resize event.

I think this logic can be improved in some way. Maybe adding an option to opt-out or similar could be a solution. I'm open to suggestions.

Anyhow, I've created a working [CodeSandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-196-p6re5) for you, that manually calls a `reInit` every time Embla triggers its `resize` event like so:

```js
const onSelect = useCallback(() => {
  if (!embla) return;
  setSelectedIndex(embla.selectedScrollSnap());
  setPrevBtnEnabled(embla.canScrollPrev());
  setNextBtnEnabled(embla.canScrollNext());
}, [embla, setSelectedIndex]);

const onInit = useCallback(() => {
  if (!embla) return;
  onSelect();
  setScrollSnaps(embla.scrollSnapList());
  setSelectedIndex(embla.selectedScrollSnap());
}, [embla, onSelect, setSelectedIndex]);

useEffect(() => {
  if (!embla) return;
  onInit();
  embla
    .on("resize", embla.reInit)
    .on("select", onSelect)
    .on("reInit", onInit);
  }, [embla, onInit, onSelect]);
```

Let me know if it helps.

Best,
David

**Comment by stianmartinsen** [comment]
This makes total sense, thank you! :)

**Comment by davidcetinkaya** [comment]
@stianmartinsen just to confirm, you did see the [CodeSandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-196-p6re5) I created right?

Cheers

**Comment by stianmartinsen** [comment]
Yes, much appreciated! It’s all working perfectly for me now 🤩👍
