### ISSUE TITLE
The slider missing autoplay option

### ISSUE THREAD

**Issue by omarkhatibco** [davidcetinkaya/embla-carousel#2]
Hi @davidcetinkaya 

It's would be good if you add autoplay option too.

Thanks for this awesome slider !

**Comment by davidcetinkaya** [comment]
Hi @omarkhatibco,

I'm planning on publishing more examples soon so I'll be sure to include an autoplay example.

**Comment by omarkhatibco** [comment]
Thanks! @davidcetinkaya

**Comment by davidcetinkaya** [comment]
Hello Omar @omarkhatibco ,
First off, thank you for reporting this!

I've created a trivial example of how to achieve **autoplay** with Embla Carousel in [this CodeSandbox](https://codesandbox.io/s/embla-carousel-autoplay-4yhr2). I hope it helps and feel free to tweak it to your liking =).

I know, all slider plugins have autoplay. I really understand that =). But since Embla Carousel’s purpose is to provide tools for building great carousels rather than having a bunch of features out of the box, I'm not going to add this into the Embla core unless it does get a lot of traction. I hope you understand.

With that said, feel free to ask any questions and don't hesitate to open a new issue again if you think Embla is missing an important tool or feature.

Thank you!

**Comment by davidcetinkaya** [comment]
Hi Omar @omarkhatibco,

Have you had the chance to check out the [CodeSandbox](https://codesandbox.io/s/embla-carousel-autoplay-4yhr2) link and my response above?

Cheers 👍🏻

**Comment by omarkhatibco** [comment]
Hi @davidcetinkaya 
Yes I tested it, and it works great! 

Thank you, this Example is what I need.

**Comment by davidcetinkaya** [comment]
Hello Omar @omarkhatibco,

I’m glad it helped 🙂!

Cheers 👍🏻

**Comment by nithiz** [comment]
Hey @davidcetinkaya , the codesandbox link is dead. Could you create a new one? :)

**Comment by nithiz** [comment]
Woops, i noticed there is an example on the examples page. For future reference: https://codesandbox.io/s/embla-carousel-autoplay-vanilla-e5ihq

**Comment by davidcetinkaya** [comment]
@nithiz @omarkhatibco, FWIW, an [autoplay plugin](https://www.embla-carousel.com/plugins/autoplay/)  is available as of v6.

- [v6 release details](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v6.0.0)

Best,
David

**Comment by omarkhatibco** [comment]
Hello @davidcetinkaya,

That's great thank you !
