### ISSUE TITLE
React carousel brokes when using css rotation

### ISSUE THREAD

**Issue by ProxyJoshua** [davidcetinkaya/embla-carousel#213]
### Bug is related to

- [ ] The Vanilla JavaScript version
- [x] The React version
- [ ] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Embla Carousel version

- v4.5.3

### Describe the bug

- The slide has a "wrong offset" when you use transform: rotate([x]deg);

### CodeSandbox

- https://codesandbox.io/s/embla-carousel-autoplay-react-forked-l45c1

### Steps to reproduce

1. Go to SandBox
2. Apply transform rotate to any parent div
3. See error

### Expected behavior

- To work properly when you scroll to others slides

### Additional context

- In the first slide the error doesn't appear, you have to scroll
![image](https://user-images.githubusercontent.com/56043504/131716258-f1a84a9e-ac33-49be-9946-21524128deaa.png)

**Comment by davidcetinkaya** [comment]
Hi Joshua (@ProxyJoshua),

Embla reads the container and slide sizes upon initialisation in order to place and align the slides correctly. So this is simply happening because transforms like scale, rotate and similar alter the element.getBoundingClientRect() values of an element. Why do you think this library should be responsible for figuring out what kind of transforms you've applied to your carousel elements and make a lot of calculations to try to fix this?

A better solution is to apply the transforms once Embla has been initialised.

Add a new state like so:

```js
const [emblaReady, setEmblaReady] = useState(false);
```

And change this:
```js
useEffect(() => {
  if (!embla) return;
  onSelect();
  embla.on("select", onSelect);
  embla.on("pointerDown", stop);
}, [embla, onSelect, stop]);
```

Into this:
```js
useEffect(() => {
  if (!embla) return;
  onSelect();
  embla.on("select", onSelect);
  embla.on("pointerDown", stop);

  setEmblaReady(true);

  embla.on("resize", () => {
    setEmblaReady(false);
    setEmblaReady(() => {
      embla.reInit();
      return true;
    });
  });
}, [embla, onSelect, stop]);
```

And don't forget to apply the transform when Embla is ready like so:

```jsx
<div
  className="embla"
  style={{ transform: emblaReady ? "rotate(-5deg)" : "none" }}
>
  ...
</div>
```

David

**Comment by ProxyJoshua** [comment]
Nice! It did work! maybe this can be on the docs if someone wants to apply css in this way.

**Comment by davidcetinkaya** [comment]
@ProxyJoshua feel free to make a contribution. Adding a page to the docs is as easy as writing a bit of markdown. You can add it under [guides](https://github.com/davidcetinkaya/embla-carousel/tree/master/packages/embla-carousel-docs/src/content/pages/guides) and call it `css-transforms.md` or similar.

Best,
David
