### ISSUE TITLE
Double row grid layout causes omitted behavior of the carousel

### ISSUE THREAD

**Issue by viktordanko** [davidcetinkaya/embla-carousel#219]
### Bug is related to

- [ ] The Vanilla JavaScript version
- [ ] The React version
- [x] The Embla Carousel core (all versions)
- [ ] Documentation website
- [ ] Other

### Embla Carousel version

- v4.5.3

### Describe the bug

- Double row grid layout causes omitted behavior of the carousel

### CodeSandbox

- https://codesandbox.io/s/embla-carousel-default-react-forked-8q5ql

### Steps to reproduce

1. Go to CodeSandbox link
2. Click on NextButton, wait a little bit, click again
3. Repeat previous step
4. You can see, that after first click, behavior of the carousel is fine, but after second click it doesn't slide.

### Expected behavior

- On every click on NextButton/PrevButton, carousel slides.

### Additional context

- Thanks 🙏 and fingers crossed! 🤞

**Comment by davidcetinkaya** [comment]
Hi @viktordanko,

Thanks for your question. This is happening because you're stacking your slides on top of each other with CSS like so:

<img width="600" alt="css grid" src="https://user-images.githubusercontent.com/11529148/134320407-5918d0d4-ebf8-45d5-8e69-8a637d52ebcf.png">

As you can see on that screenshot, **Slide 1** and **Slide 2** will have the exact same position because they're on top of each other. You should change your CSS and HTML so that the `.embla__container` class only stacks slides horizontally, and then you can add a vertical grid inside each slide instead.

Best,
David

**Comment by viktordanko** [comment]
Thanks, David! 
I adjusted `slidesToScroll` options and it works like a charm :]
