### ISSUE TITLE
embla react v 6.0.1 embla.dangerously get engine is not a function

### ISSUE THREAD

**Issue by fjobeir** [davidcetinkaya/embla-carousel#264]
### Bug is related to

- [x] embla-carousel-react

### Embla Carousel version

- v6.0.1

### Describe the bug

Hello, I am trying to apply that sample in my website
https://codesandbox.io/s/embla-carousel-scale-react-j2ulk?file=/src/js/EmblaCarousel.js
I am getting an error messages saying that "embla.dangerously get engine is not a function"
I changed the version to 5.0.1 and it worked, but I do not want to change the version

**Comment by davidcetinkaya** [comment]
Hi @fjobeir,

That’s because `dangerouslyGetEngine` has been renamed to `internalEngine` in v6 as described in the [release details](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v6.0.0). So this is not a bug.

Please update all calls to `dangerouslyGetEngine` to `internalEngine` I’m your code.

Kindly
David

**Comment by fjobeir** [comment]
the method dangerouslyGetEngine has been renamed
https://github.com/davidcetinkaya/embla-carousel/releases/tag/v6.0.0

**Comment by fjobeir** [comment]
Hello David
thanks for your response.
yes, it is not a bug but I had to choose either a bug or a feature request.

**Comment by davidcetinkaya** [comment]
No worries @fjobeir. Just wanted to be clear. I’ll update the CodeSandboxes so they all use v.6 when possible. Just haven’t had the time yet.
