### ISSUE TITLE
Carousel skips items and glitches visually

### ISSUE THREAD

**Issue by WalkingPizza** [davidcetinkaya/embla-carousel#273]
### Bug is related to

- [ ] embla-carousel (core package)
- [x] embla-carousel-react
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- v6.1.1

### Describe the bug

I have three carousels on my page:
- The main carousel, showcasing different images.
- The zoomed carousel, which users can open by clicking on a button in one of the main carousel's slides, and acts as a full-screen copy of the main carousel.
- The thumbnails carousel, which is placed underneath the zoomed carousel.

The main carousel works fine, and so does the thumbnails one, but I have noticed a very weird glitch in the zoomed one.
Basically, although the navigation buttons work fine (using `scrollPrev` and `scrollNext`), swiping from one image to the other does not work, as the carousel skips items and glitches visually.

### Loom

You can see the issue [here](https://www.loom.com/share/b4c3a9329dd74fb7af89581b1912e9e2).

### Expected behavior

- Users should be able to swipe without skipping items nor glitching the carousel.

### Additional context

**If I alter the carousel configuration settings while in development mode in my React app and save the changes, the carousel starts working properly.**

- Main carousel settings
```js
{ align: "center" }
```
- Zoomed carousel settings
```js
{ align: "center" }
```
- Thumbnails carousel settings
```js
{ align: "center", dragFree: true }
```

**Comment by davidcetinkaya** [comment]
Hi @WalkingPizza,

It's almost impossible for me to guess my way to why you're experiencing this problem, because you haven't provided a CodeSandbox that clearly demonstrates the issue. I can't debug anything without any code. 

> If I alter the carousel configuration settings while in development mode in my React app and save the changes, the carousel starts working properly.

My guess would be that you need to run `embla.reInit()` as soon as a user triggers the zoomed carousel, in order for Embla to pick up all the container and slide dimensions correctly, after the zoom has finished. 

Please take a moment to read the **Bug reports** section in the [Contribution guidelines](https://github.com/davidcetinkaya/embla-carousel/blob/master/.github/CONTRIBUTING.md#bug-reports).

Best,
David
