### ISSUE TITLE
stack slides on top of each other

### ISSUE THREAD

**Issue by PhilippLiebhart** [davidcetinkaya/embla-carousel#274]
I am so so happy with embla carousel.. so far... it's the best i could find on the internet!
But i am having trouble tweaking the animation to fit my needs.

### Feature request is related to
- [x] embla-carousel-react

### Describe the solution you'd like

I want to achieve that slides stack on top of each other and slide out/in to reveal the next/previous slide. 
please check the video.. i can't show more of this but i think/hope it's quite clear!

please check out: [video of what to achieve](https://www.dropbox.com/s/044f93om3lx138l/sx.mov?dl=0)

i hope it's clear what i try to achieve!
I really don't know how to even start to tweak the animation...

thank you so much in advance!!!

**Comment by nikrowell** [comment]
Hi @PhilippLiebhart 👋

Agreed - best carousel I've found! 

The cropping on your video made it hard to see exactly what you're going for, but looks / sounds like a variation of @davidcetinkaya's [parallax example](https://www.embla-carousel.com/examples/inspiration/#parallax). Here is a [CodeSandbox](https://codesandbox.io/s/embla-carousel-parallax-react-forked-uwdql) fork of that demo that has a full reveal effect - hope this helps! Here were the main changes:
* Removed the gap between slides
* Update slide styles to `min-width: 100%` to fill the viewport
* Changed the `onScroll` callback to take the number of slide nodes into account (line 48)
* Changed `PARALLAX_FACTOR` to 1.0 (if this is less than 1, it has a nice slide / reveal combo)

**Comment by PhilippLiebhart** [comment]
@nikrowell thank you so so much for the very quick help!!!
@davidcetinkaya approach it's very close to what i am looking for! 

But I don't want to "crop"-away the currentslide like it is in davids example.
-  instead the current slide should slide to the left/right to reveal the next/prev slide.

just found an example of exaclty what i need!
[example](https://programmer.help/images/blog/2ef074f667d94fffd3691577482d8392.jpg)

is this possible?
i will have a look at davids approach maybe i can tweak it a bit... but i am not too experienced maybe @davidcetinkaya could help out? 

thank you guys so much!

**Comment by nikrowell** [comment]
@PhilippLiebhart you're welcome!
Let me put some thought into how to pull that off with Embla... David might have some thoughts too (and obviously a much better understanding of the carousel capabilities 😀)

**Comment by davidcetinkaya** [comment]
Hi @PhilippLiebhart,

Thanks for your feature request. This is a friendly reminder: Did you read [this](https://github.com/davidcetinkaya/embla-carousel/issues/187#issue-873669552) before creating this request? Sometimes, nice and awesome people like @nikrowell will help you with what you want to achieve, without any compensation. This is admirable in my opinion.

And as much as I would like to help everyone with their feature requests, I can’t. I have two kids now, and my spare time is very limited. And to be frank, this project isn’t paying my bills. The little unpaid spare time I have, I want to spend on features I choose, and that includes other projects too.
And even if you’re willing to provide funding for your feature request, I can never give you an ETA.


What you want to achieve should be quite doable utilizing the `embla.internalEngine()` method. But in order to achieve that, it requires some knowledge about how the carousel works internally.

I hope you understand.

Best,
David

**Comment by J3m5** [comment]
Hello,

Is there any progress on this feature? 
It's exactly what I'm looking for.

Thanks

**Comment by xnslx** [comment]
> Hi @PhilippLiebhart 👋
> 
> Agreed - best carousel I've found!
> 
> The cropping on your video made it hard to see exactly what you're going for, but looks / sounds like a variation of @davidjerleke's [parallax example](https://www.embla-carousel.com/examples/inspiration/#parallax). Here is a [CodeSandbox](https://codesandbox.io/s/embla-carousel-parallax-react-forked-uwdql) fork of that demo that has a full reveal effect - hope this helps! Here were the main changes:
> 
> * Removed the gap between slides
> * Update slide styles to `min-width: 100%` to fill the viewport
> * Changed the `onScroll` callback to take the number of slide nodes into account (line 48)
> * Changed `PARALLAX_FACTOR` to 1.0 (if this is less than 1, it has a nice slide / reveal combo)




Hello @PhilippLiebhart I am using the codesandbox that you created as an example. It is very useful. But I implement it as vertical scroll. I notice that if you slightly change `loop: false`, then when you swipe to the next slide, the previous/current slide will shift a little bit. Do you have any idea how to fix it? Thank you so much for your wonderful example!

**Comment by spencercap** [comment]
A card stacking effect between "slides"/cards would be amazing! 
akin to this SwiperJS mode: https://swiperjs.com/demos#effect-cards 

I understand it's a heavy lift for an open source project @davidjerleke 
amazing work on this repo already 👏 and without getting into the weeds, what are the broad strokes needed to pay attention to in the `embla.internalEngine()` ?

**Comment by xnslx** [comment]
@spencercap I ended up moving away from Embla and implemented the carousel using GSAP instead — and to my surprise, it was actually quite straightforward! Here's a [demo](https://carousel-sanity.vercel.app/) inspired by Zara's site. The user can swipe horizontally to navigate the parent carousel (category level), and then vertically within each parent item to view its child slides.

I used Sanity.io to upload images and videos — not essential to the setup, but it made playing around with content more fun.

**Comment by davidjerleke** [comment]
@spencercap Thanks! I appreciate the kind words.

I’m currently working on v9, which will move away from JavaScript-based animations in favor of CSS-driven ones. It’s a significant context switch, so implementing something like the card stacking effect—while very doable—isn’t something I can take on right now. The main blocker isn’t complexity but time. I’m the sole maintainer/developer on this project and juggling everything without much in the way of sponsorship.

That said, the `embla.internalEngine()` exposes a lot of what you’d need to build this kind of effect yourself, particularly around slide indexes, scroll progress, and transform handling. 

The [tween examples](https://www.embla-carousel.com/examples/predefined/#tween-examples) in the docs demonstrate how to use scroll progress to animate slides, while the iOS picker examples show how to fully override the default scroll behavior. Both approaches highlight key techniques you’d need to build the card stacking effect you’re aiming for.

**Comment by spencercap** [comment]
@davidjerleke awesome! happy to hear abt a css version for v9! 

perhaps i've revisit the cards mode myself after this significant update. 
i bet it'd be possible w the new-ish css scroll-timeline api / syntax.
imagine... rotating + translating + updating z-index of cards/slides based on an invisible scroll container offset w some math for number of items etc. css + gpu magic. 
check out the demos here if you haven't already: https://scroll-driven-animations.style/

**Comment by ndimatteo** [comment]
I managed to get something like this to work building off the "Scale" tween example! Sharing here in case anyone wants to jump in and see where it could be improved: 

https://codesandbox.io/p/sandbox/embla-carousel-card-stack-react-wip-2r3hg4

**Some limitations worth noting:**
- In order to get the correct number of duplicated slides during `loop` the slide _width_ needs to be small enough to show that many additional slides visible in view equal to the fixed stack `depth` of `3`
- Because of the above, in order to get a better _visually_ sized carousel the size of the `.embla__viewport` is doubled (`200%`).
- you have to have a _minimum_ number of slides equal to `5` (`depth * 2 - 1`), otherwise the stack animation breaks (not sure why?)

**Some improvments I would love to get some help with:**
1. Be able to set the stack `depth` to whatever you want, rather than fixed at `3`
2. Being able to force the engine to duplicate more than one slide when near the end/beginning to keep stack depth consistent
3. Avoid broken animations when slide length is less than the stack depth

**Comment by spencercap** [comment]
nice one @ndimatteo !
