### ISSUE TITLE
`slidesInView` is one select event behind

### ISSUE THREAD

**Issue by vajkri** [davidcetinkaya/embla-carousel#291]
### Bug is related to

- [ ] embla-carousel (core package)
- [X] embla-carousel-react
- [ ] embla-carousel-autoplay
- [ ] embla-carousel-auto-height
- [ ] embla-carousel-class-names
- [ ] embla-carousel-docs (documentation website)

### Embla Carousel version

- v6.2.0

### Describe the bug

- `slidesInView` (and actually also `slidesNotInView`) seem to be one select event too late. Both with single and multiple items in view.

### CodeSandbox

- https://codesandbox.io/s/confident-kilby-n5wcti?file=/src/App.tsx

### Steps to reproduce

1. Go to line 52 in 'App.tsx'
2. Open console
3. Click on "Next" and/or "Prev" a couple of times
4. Observe, that `slidesInView` is one click behind

### Expected behavior

- I'd like to have `slidesInView` in sync with what's actually in view.

Thanks in advance

**Comment by davidcetinkaya** [comment]
Hi @vajkri,

Thank you for your question. By default, the `slidesInView` method returns the slides in view at the current carousel scroll location when the method is called, and not the target/destination. This is useful when you want fine grain control and want to track what slides are in view when listening to the `scroll` event. But I think you’re looking for the [`target`](https://www.embla-carousel.com/api/methods/#slidesinview) parameter:

- _Set the **target** parameter to `true` when you want to get the slides visible at the scroll destination instead of the current scroll location._

An example:

```js
function logSlidesInView() {
  console.log(embla.slidesInView(true));
}

embla.on('select', logSlidesInView);
embla.on('pointerUp', logSlidesInView)
```

Note that I added `pointerUp` event because if you have a carousel with [dragFree](https://www.embla-carousel.com/api/options/#dragfree)  enabled, dragging might not change the selected snap at all times, but it could change which slides are in view and not.

Let me know if it helps.

Best,
David

**Comment by vajkri** [comment]
Perfect, thanks your for quick reply. Passing `true` solved it for me :-)

**Comment by PurviJha** [comment]
HI @davidcetinkaya i updated my carousel from 2.4.4 to its latest version  in my carousel  i have button on images consider if i have button on 4th image  and while tabbing  i got to 4th button so in that case my carousel scrolled to 4th slide but is-selected class is not adding to that slide . I also checked select  event is also not initiating in tabbing case. in my older version i was not facing this issue  select was also initiated while tabbing as well as is-selected  class was also adding automatically. this is a accessibility issue for me. do we have a better way.

**Comment by michaelaltmann** [comment]
@davidjerleke  This answer suggests that `slidesInView` takes a target argument that can be true or false.  That does not seem to be in the current API.

**Comment by niteshsrivats** [comment]
Hey @davidjerleke, what's the solution for this using the latest APIs?

**Comment by davidjerleke** [comment]
@niteshsrivats please check the [lazy load example](https://www.embla-carousel.com/examples/predefined/#lazy-load) in the docs out. It uses the `slidesInView` event which is the recommended way of doing it with the current API.

**Comment by chorgen** [comment]
Just copy/pasted the code from the lazy load example, and it looks like its still one "select event" behind like OP mentioned. 

I'm trying to "set" the first element/index in the `slidesInView` array as the active element (and "disable" all the other elements). But this doesnt work when `slidesInView` gives me the response from the previous scroll event. Maybe there is a better way of doing this?

**Comment by davidjerleke** [comment]
@chorgen maybe I’m misunderstanding you, but there’s no `select` event that’s one step behind anymore, because that’s not the way to check for slides in view. This API change was introduced long ago.

Use the `slidesInView` event instead. Please see my previous [comment](https://github.com/davidjerleke/embla-carousel/issues/291#issuecomment-2507800892) that has a link to the example in the docs.

**Comment by chorgen** [comment]
> @chorgen maybe I’m misunderstanding you, but there’s no `select` event that’s one step behind anymore, because that’s not the way to check for slides in view. This API change was introduced long ago.
> 
> Use the `slidesInView` event instead. Please see my previous [comment](https://github.com/davidjerleke/embla-carousel/issues/291#issuecomment-2507800892) that has a link to the example in the docs.

Sorry, I was a bit quick to comment on the example. I think I copied the wrong part. And it looks like I deleted my comment here just as you wrote me back.
