### ISSUE TITLE
New Feature: Accessibility

### ISSUE THREAD

**Issue by SLMNBJ** [davidcetinkaya/embla-carousel#6]
Would be nice to have the slider accessibile, maybe with custom labels (i18n).

**Comment by davidcetinkaya** [comment]
Hi @SLMNBJ ,
What do you mean by accessibility? Like **aria-hidden=""** labels?

**Comment by SalmenBejaoui** [comment]
Hi @davidjerleke,
Yes, I'm talking about the aria-labels. For example, when i navigate using the VoiceOver, i would like to header next slide, previous slide (maybe with custom labels for multiple languages). Same for the dots navigation.

**Comment by davidcetinkaya** [comment]
Hi @SLMNBJ,
Thanks for the clarification!

If I'm to add this to the Embla core, I'd need some kind of **draft or a well specified suggestion** on how to implement this (based on web accessibility standards for carousels).
Emblas purpose is to provide the **tools** to build great physics-based carousels rather than providing a huge set of features out of the box, so any added feature should be as generic and reusable as possible.

With that said, you do have access to a lot of stuff by using the Embla API to build your own solution and add your custom accessibility labels:

```javascript
const node = document.getElementById('embla')
const embla = EmblaCarousel(node)

embla.getContainer() // Gets the current container element
embla.getSlides() // Gets the slides as an array of elements
embla.getSelectedIndex() // Gets the current selected slide index. First slide starts at index 0.
// etc.
```

**Comment by davidcetinkaya** [comment]
I’m closing this due to lack of response. Thank you for reporting this 👍🏻!

**Comment by hotgeart** [comment]
The features needed for a carrousel a11y are described here : https://www.w3.org/TR/wai-aria-practices-1.1/examples/carousel/carousel-1.html

**Comment by mantagen** [comment]
I'd be surprised if adding a11y attributes added much too much to the bundle (though 1. I could be wrong, and 2. it's subjective).
a11y's perceived importance is growing, and it could be even be an opt-out/opt-in import which with tree shaking wouldn't affect bundle size if not used.
If it gains traction enough for it to go ahead I'd be very happy to contribute.

**Comment by davidjerleke** [comment]
Hi @mantagen,

Thank you for sharing your thoughts. It depends on how much accessibility we want to implement into the core. If it's only the `aria-hidden` labels, it may not add much to the bundle size.

Recently, I've considered adding accessibility stuff to the library core. I'm thinking something along these lines:

- Toggling `aria-hidden` labels for slides.
- Allowing for keyboard navigation with arrows as mentioned in #53. Although I'm not sure about adding this.

...and more. But if I'm to proceed with that suggestion, I'm considering to remove the following **options**:

- `selectedClass`
- `draggableClass`
- `draggingClass`

...in order to keep the library lightweight. I've raised this before releasing [major version 3 here](https://github.com/davidcetinkaya/embla-carousel/issues/67#issue-635152035), and at that time, Embla users voted to keep these. But only 10 people voted so it's not like people seem to care too much about it. Also, it seems like React users don't utilize these options much.

What's your thoughts about my suggestion?

Best,
David

**Comment by mantagen** [comment]
This sounds good to me. I would remove those classes, however I'm pretty much exclusively using css-in-js at the moment, whereas if I was using classes I may be of a different opinion! To me, some small accessibility additions seem more like core functionality than classes.

Following from what @hotgeart has said, the basic `aria` attributes to add would be

- `aria-roledescription="carousel"` on the "viewport" element (the root element to which `emblaRef` is passed)
- `aria-roledescription="slide"` on each slide element
- `aria-label="{i} of {n}"` on each slide element (where aria label hasn't been provided by the user?)
- `aria-live="polite"` on the element containing the slides
  - however, if the user has put the carousel on a timer, so that it slides automatically, then this should be `aria-live="off"`, otherwise the user is constantly alerted to slide changes
  - this makes me wonder if it should be up to the user to set this attribute
- `aria-hidden="true"` on slides which are not visible
  - for most cases this will apply to all but the current slide, however, in the cases in which more than one slide is visible, this logic is no longer correct
  - perhaps in this case the user could override the `aria-hidden` attribute?

I've seen that swiper are working on improving accessibility too, https://github.com/nolimits4web/swiper/issues/3149, though obviously it is not a lightweight solution -- eg. includes navigation etc etc -- so not all of their criteria apply here, it might be worth looking at their discussion. 

I'm wondering if `aria-live` and `aria-hidden` might be beyond the scope of this package, since without proper use by the person implementing the slider, they could actually make accessibility worse.

@hotgeart @SLMNBJ what do you think?

**Comment by davidjerleke** [comment]
Thank you for your input @mantagen.

If you don't mind me asking, where did you get that nice list of `aria` attributes? Also, thanks for the link to the Swiper accessibility issue, that will probably help a lot.

> I'm wondering if `aria-live` and `aria-hidden` might be beyond the scope of this package, since without proper use by the person implementing the slider, they could actually make accessibility worse.

I think `aria-live` is beyond scope because **autoplay** is actually not an Embla Carousel core feature. This is because the **autoplay** [setup](https://davidcetinkaya.github.io/embla-carousel/examples#inspiration) on the examples page is a demonstration of how to extend Embla with that feature.

But Embla tracks slides in and out of view so I'm thinking that maybe the `aria-hidden` attributes should be a core feature. Do you have any additional information about how to use this incorrectly and make accessibility worse, so we can avoid doing it wrong?

Best,
David

**Comment by mantagen** [comment]
Hi David,

That list is essentially from https://www.w3.org/TR/wai-aria-practices-1.1/examples/carousel/carousel-1.html

There are two potential problems with adding `aria-hidden` that I can think of:
1. For a carousel in which the width of the slide is eg. 20% (i.e. multiple slides fit within the carousel viewport), all the visible slides should have `aria-hidden="false"`. It would need a programmatic way of determining whether the slide is visible, for instance: `gatsby-image` handles it like:
- https://github.com/gatsbyjs/gatsby/blob/cf3430462748cecdfb4b9f6b61285534fb4a2ea9/packages/gatsby-image/src/index.js#L352 


2. If slides contain any focusable elements like `a` or `button`, and the slide has `aria-hidden="true"` then the browser can focus on these elements, but the focus will not be announced by a screen reader. See:
- https://www.accessibility-developer-guide.com/knowledge/aria/bad-practices/#hiding-focusable-elements 
- https://www.w3.org/TR/using-aria/#fourth


I'd say that perhaps (1) is not such a big deal, but that (2) is. If the library added a `tabIndex: -1` to all focusable elements of the inactive slides, *and* there was a something in the documentation saying that the carousel was intended only to have one slide per view, then maybe this would get around both these issues, but this is presumably beyond core scope.

This is why I'm currently of the opinion that adding `aria-hidden` to the core of this library could not be a good idea.

**Comment by mantagen** [comment]
For further reference: https://act-rules.github.io/rules/6cfa84

Also, I've just seen that the carousel slides on tab press if new focus is within the following slide. I'm not sure what the implications of this are... as in, I'm not sure if it is okay to dynamically change from `aria-hidden="true"` to `aria-hidden="false"` _as an element receives focus_.

**Comment by davidjerleke** [comment]
Thank you for the further information @mantagen.

That's helpful 👍. I'm thinking that we should create a CodeSandbox with all the desired accessibility features. For example, we can use the default [React sandbox](https://codesandbox.io/s/embla-carousel-default-react-88p7h) as a starting point. I'm hoping that by the time we're done with the sandbox, we should have a clear picture of what should go into the Embla core and not.

> Also, I've just seen that the carousel slides on tab press if new focus is within the following slide. I'm not sure what the implications of this are... as in, I'm not sure if it is okay to dynamically change from aria-hidden="true" to aria-hidden="false" as an element receives focus.

When I implemented this, I thought it would be a good idea to mimic the browser behavior to some extent, by brining the focusable element into view. But I'm open to other suggestions.

Best,
David

**Comment by mantagen** [comment]
Yes I believe that content of non-visible slides should not be tabable:
> The user cannot tab to any of the interactive elements in hidden panels. The tabindex="-1" attribute should be added dynamically to these elements. The attribute would be removed when the associated panel is visible.
https://www.accede-web.com/en/guidelines/rich-interface-components/carousels/

This article also suggests to add `aria-hidden="true"` to non-visible slides. 

Yes, let's start from the sandbox, and see where we get.

**Comment by Wikgabja** [comment]
Hello,
I would like to change the aria-hidden value from false to true  for selected slide, I mean the slide with "is-selected" class. Could you let me an example how to do that in vanilla script?

**Comment by davidcetinkaya** [comment]
Hi @Wikgabja,

You can use the same approach as the selected class toggling functions [here](https://github.com/davidcetinkaya/embla-carousel/blob/master/packages/embla-carousel/src/components/index.ts#L110-L116). And don’t forget to attach this function to the select and pointerUp event [like this](https://github.com/davidcetinkaya/embla-carousel/blob/master/packages/embla-carousel/src/components/index.ts#L93-L96).

I hope that helps.

I’ll soon release v6 which I think can be somewhat of a game changer for all Embla users that are frustrated about missing features (like accessibility). v6 comes with a plugin system that will enable Embla users to use plugins to extend it beyond its core functionality. And anyone will be able to write and share their own plugins too:

- #229

More information coming as soon as v6 has been released.

**Comment by patricknelson** [comment]
Just curious since I'm reviewing this carousel for use on our site: Are there any good a11y plugins available now? I noticed the plugin route was suggested but none were mentioned here or on the site, which is why I figured I'd ask.

Keyboard a11y isn't too bad (as long as you're sighted) but screen readers  just identify everything right now as "button" so it's not helpful yet. Not sure if you have to dig into the guts in order to announce which bullet/dot you're on, for example.

**Comment by davidjerleke** [comment]
Hi @patricknelson,

No plugin yet. But the secret project will include accessibility:

- #504 

I can’t give an ETA on when it’s ready though because it’s under development. If you have to build something soon and want to use this library you have to do it yourself.

**Comment by patricknelson** [comment]
Ok. Thanks for the feedback.

Just curious: What’s the point to having a “secret” project in open source? Why not just describe what it is and be frank that it’s just incomplete or the concept is under development?

**Comment by davidjerleke** [comment]
@patricknelson because I don't want feedback and any interference before I have a working proof of concept or an experimental feature ready.

**Comment by davidjerleke** [comment]
Calling all accessibility experts 👋! Could anyone help me with creating a complete list of things that are required to create a fully accessible carousel? It's for the accessibility option that will be available in the [carousel generator](https://www.embla-carousel.com/examples/generator/).

**Comment by hotgeart** [comment]
@davidjerleke everything you need is in the example of the W3C : https://www.w3.org/WAI/ARIA/apg/patterns/carousel/examples/carousel-1-prev-next/

**Comment by patricknelson** [comment]
@davidjerleke Makes sense. The updated description helps a bit too. Looks like an interesting project.

**Comment by nwidynski** [comment]
Hey guys,

thought i would give this a shot, so here is my attempt:  [https://github.com/nwidynski/embla-carousel-aria](https://github.com/nwidynski/embla-carousel-aria)

- [X] ARIA-spec accessibility adhering to [W3 ARIA carousel](https://www.w3.org/WAI/ARIA/apg/patterns/carousel/examples/carousel-1-prev-next/)
- [X] Localization of all ARIA properties
- [X] Adobe-inspired automatic focus shift
- [X] Full screen-reader support

**Comment by alvinkonda** [comment]
Accessibility should be at the core of the plugin, otherwise, it's a No for me.

**Comment by davidjerleke** [comment]
@alvinkonda if you don’t want to understand [this](https://github.com/davidjerleke/embla-carousel/discussions/316#discussioncomment-2823006), then have fun finding a different library.

**Comment by patrick-schneider-latori** [comment]
What is the status here? I am willing to move from Swiper to Embla, but since a11y is currently not available I don't this library is an alternative atm for me, although I really love this package 👍🏼

**Comment by davidjerleke** [comment]
Hi @patrick-schneider-latori,

Thanks for your question. Please help me understand what are you looking for? A convenient solution where the package does everything for you? Or simply an example setup that's a11y compliant?

**Comment by davidjerleke** [comment]
Hi everyone 👋,

For those still following along, there’s a **work-in-progress** `embla-carousel-accessibility` plugin available (**React** demo but the plugin is library agnostic):

* [🔗 App demo](https://49qxpg.csb.app/)
* [🔗 CodeSandbox editor](https://codesandbox.io/p/sandbox/embla-carousel-loop-react-forked-49qxpg?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A34%2C20)

The accessibility approach is based on these resources and testing insights:

* Mainly this: [How to build a more accessible carousel or slider](https://dev.to/jasonwebb/how-to-build-a-more-accessible-carousel-or-slider-35lp) (especially [these key observations](https://dev.to/jasonwebb/how-to-build-a-more-accessible-carousel-or-slider-35lp#comment-1igai))
* [WAI-ARIA carousel example with prev/next controls](https://www.w3.org/WAI/ARIA/apg/patterns/carousel/examples/carousel-1-prev-next/)
* [A step-by-step guide to building accessible carousels (Smashing Magazine)](https://www.smashingmagazine.com/2023/02/guide-building-accessible-carousels/)

🙏 I’d love help testing this plugin with different accessibility tools (screen readers, keyboard navigation, voice control, etc.). If you’re willing to try it out, I’d really appreciate hearing about your experience and any issues you run into. Your feedback will help make the carousel more usable for everyone.

---

### The plugin currently supports:

* Dot navigation buttons
* Previous/next controls
* Keyboard focus management
* Autoplay handling
* Screen reader live region announcements
* Grouped slides via the `slidesToScroll` option

---

### Why the tabbing pattern isn't used

I decided **not** to follow the tabbed interface pattern for carousel dots.

During accessibility testing, others (like the team at Accessible360) have found that the tabbed approach is often confusing and unintuitive for real users:

* Carousels don’t look like tabbed interfaces, so low-vision and keyboard users don’t expect tab-style controls or key commands.
* Screen reader users rarely encounter tabs that control content placed *before* them in the DOM. Since `aria-controls` has little real support, the connection between dots and slides often isn’t clear.
* Programmatically moving focus to slides can also feel disruptive, and risks violating WCAG 3.2.2 (change of context on input).

On top of that, the **“one dot per slide” tab pattern breaks down when slides are grouped** (e.g. when using `slidesToScroll > 1`). In those cases, a dot doesn’t map neatly to a single slide, which makes the tab/tabpanel relationship invalid.

Instead, I treat dots as **buttons** with clear labels that announce which slides belong to each snap. For example:

```js
const options = {
  dotButtonAriaLabel: (
    hasAnyGroupedSlides,
    firstSlideIndex,
    lastSlideIndex,
    totalSlides,
    selectedSnapIndex,
    totalSnaps
  ) => {
    const slide = firstSlideIndex + 1
    const lastSlide = lastSlideIndex + 1
    const isSlideGrouped = firstSlideIndex !== lastSlideIndex
    const groupInfo = `(group ${selectedSnapIndex + 1} of ${totalSnaps})`

    if (!hasAnyGroupedSlides) {
      return `Go to slide ${slide} of ${totalSlides}`
    }

    if (!isSlideGrouped) {
      return `Go to slide ${slide} of ${totalSlides} ${groupInfo}`
    }

    return `Go to slides ${slide}-${lastSlide} of ${totalSlides} ${groupInfo}`
  },
}
```

This way, users always get an accurate announcement like 👉 *“Go to slides 3–4 of 10 (group 2 of 5)”*,
which is both descriptive and works equally well whether slides are grouped or not.

---

⚠️ Disclaimer: The code in the demo (mainly the plugin file) is currently messy and unpolished. It’s meant to illustrate functionality and accessibility patterns rather than serve as production-ready code. I’ll be cleaning it up and refining the implementation in future updates.

**Comment by nwidynski** [comment]
@davidjerleke I'm currently amidst work on a Carousel in React Spectrum and got some insights to share. The biggest issue I currently see with that plugin is that implementations using `aria-hidden` should throw or log a warning when interactive content is found in slides. This is because focus should never land on `aria-hidden` subtrees and `aria-hidden` does not prevent that, unlike `inert`. Unfortunately using `inert` on slides becomes unintuitive for sighted users, who expect interactive content to be interactive when in view (e.g. multiple visible slides).

That being said, the plugin is still a great step forward 🥳

**Comment by davidjerleke** [comment]
@nwidynski Thanks for the feedback 🙂!

In the plugin, **all focusable elements inside a slide that isn’t currently selected are automatically disabled** by setting `tabindex="-1"`. This ensures that keyboard focus **cannot land on inactive slides,** even if they contain interactive content. Only the active slide’s focusable elements remain tabbable, so users can navigate the carousel without accidentally interacting with hidden or offscreen slides.

This approach avoids the issues you mentioned with `aria-hidden`, while still keeping visible slides fully interactive for sighted and keyboard users.

**Comment by nwidynski** [comment]
@davidjerleke `tabIndex="-1"` only removes elements from the tab sequence. It does not prevent focus through pointers, screen readers or programmatic focus. Navigation modes aren't always one or the other, users may click into a slide, then use keyboard to navigate around. 

The plugin also does not disable all interactive content, it only queries for buttons, inputs and anchor tags. Custom elements using tabIndex=0 will remain focusable, leading to the described problem.

**Comment by davidjerleke** [comment]
@nwidynski Thanks for your input 👍. You’re right — tabindex="-1" only removes elements from the tab sequence, and doesn’t prevent focus via mouse/pointer, screen readers, or programmatic calls.

What would be the best way to handle that? Would it make sense to prevent default on focus events for inactive slides, or is there a better approach?

Also, regarding programmatic focus — is that really something the library should manage? I think we should assume developers won’t try to focus elements inside inactive slides.

**Comment by nwidynski** [comment]
> What would be the best way to handle that? Would it make sense to prevent default on focus events for inactive slides, or is there a better approach?

`FocusEvent` can't be default prevented unfortunately. React Aria is setting `inert` when multiple panels are force mounted, which prevents the panel and its descendants to gain focus or raise click events. As I said, that's okay for phrasing content or when you expect users to not interact (e.g. during mount animation), but is confusing for sighted users when you want fully interactive content inside slides.

I can go into detail of what is required to enable that, but I honestly think it would be infeasible to handle in a plugin from scratch. TLDR; You would need a way to navigate and restore focus between slides, while also being able to move that focus virtually when the rotation controls are interacted with.

That's why I recommended to just throw or log a warning when focusable content is detected 👍

**Comment by davidjerleke** [comment]
@nwidynski Thanks for the detailed explanation 👍🏻.

So you mean there are ways to make inactive slides non-interactive, but the problem arises when sighted users are unable to interact with slides that are actually visible (but not canonically active)?

Just to clarify — are you suggesting that the plugin shouldn’t try to handle any focus logic at all, and instead simply throw or log a warning when it detects focusable content inside inactive slides?

I’m trying to understand if that’s the most practical approach, given the complexity of managing focus across interactive slides while keeping the experience intuitive for sighted users.

**Comment by nwidynski** [comment]
> So you mean there are ways to make inactive slides non-interactive, but the problem arises when sighted users are unable to interact with slides that are actually visible (but not canonically active)?

Exactly.

> Just to clarify — are you suggesting that the plugin shouldn’t try to handle any focus logic at all, and instead simply throw or log a warning when it detects focusable content inside inactive slides?

Yes, although maybe the roving tabindex/inert on the slides could stay. Users would be using this plugin because they care about accessibility - putting interactive content inside slides is just not accessible without major effort. If they don't care about that, then they mustn't use the a11y plugin 😅

**Comment by davidjerleke** [comment]
@nwidynski how about this approach?

- Inactive slides: tabindex="-1" so they are removed from the tab order.
- Pointer detection: Listen for touchstart (touch) and pointerdown (mouse/pen). Track the timestamp of the last pointer interaction.
- Focus handling: When a focus event happens on a slide or its children: Check the time difference between the focus and the last pointer event.
- If it’s very short → likely triggered by the pointer, allow focus.
- If not → likely keyboard or programmatic focus to an inactive slide, restore focus to the previous element.

**Comment by nwidynski** [comment]
@davidjerleke `touchstart` doesn't have broad [browser support](https://developer.mozilla.org/en-US/docs/Web/API/Element/touchstart_event#browser_compatibility) yet and I'm also not sure whether its timing is consistent across browsers and platforms. Restoring focus to the previous element may also become a focus trap and trigger announcements of the briefly focused element.

**Comment by davidjerleke** [comment]
Hi @nwidynski,
Thank you for your response 👍🏻.

> `touchstart` doesn’t have broad [browser support](https://developer.mozilla.org/en-US/docs/Web/API/Element/touchstart_event#browser_compatibility) yet and I’m also not sure whether its timing is consistent across browsers and platforms.

I actually meant `pointerup`, which should reliably cover both `mouseup` and `touchend`. From what I’ve seen, the timing is fairly consistent across browsers and platforms to detect whether those events triggered the focus.

> Restoring focus to the previous element may also become a focus trap and trigger announcements of the briefly focused element.

Yeah, that’s a fair concern. I’ll give it a try and see how it behaves in practice.

**Comment by nwidynski** [comment]
@davidjerleke Sure, just be aware of https://developer.chrome.com/blog/300ms-tap-delay-gone-away .

**Comment by davidjerleke** [comment]
> [@davidjerleke](https://github.com/davidjerleke) Sure, just be aware of https://developer.chrome.com/blog/300ms-tap-delay-gone-away .

@nwidynski I’m aware of that, but I really appreciate you pointing it out and being helpful!

**Comment by davidjerleke** [comment]
* [🔗 App demo](https://49qxpg.csb.app/)
* [🔗 CodeSandbox editor](https://codesandbox.io/p/sandbox/embla-carousel-loop-react-forked-49qxpg?file=%2Fsrc%2Fjs%2FEmblaCarousel.tsx%3A34%2C20)

---

Hi @nwidynski (and anyone interested) 👋,

Thanks so much for the great feedback so far — especially the insight about `aria-hidden` and interactive content inside slides. I’ve made some updates to the plugin and made a few intentional design decisions now, and this is how it works:

- **Non-canonically selected slides** now get `aria-hidden="true"` and all focusable children receive `tabindex="-1"`.
- To allow **visual users** to interact with focusable content inside slides that are *in view* but not canonically selected, the plugin temporarily removes `aria-hidden` on `focus` and re-applies it on `focusout`.

  - This prevents Chrome from logging warnings when pointer focus lands on elements inside `aria-hidden` containers.
- From an accessibility perspective, assistive tech should not be able to focus inside non-selected slides since they remain `aria-hidden` and `tabindex="-1"`.
- **Programmatic focus** on elements inside unselected slides is discouraged, but the plugin doesn’t prevent it — this is something I’ll call out in the docs.
- I’ve opted **not** to use `inert`, since that would prevent visual users from interacting with focusable content in non-selected but visible slides.

Would love for you to give this a try with your accessibility tools and workflows.

Thanks!

**Comment by nwidynski** [comment]
@davidjerleke Hey there, love to see these updates 👍 Here are the issues I found in testing:

- the selector for focusable nodes should be more accurate, see [here](https://github.com/adobe/react-spectrum/blob/6c17b7c603f3fd617032f05e94a1f6815b564e35/packages/%40react-aria/utils/src/isFocusable.ts#L37)
- `focusin` and `focusout` events on slides should be processed in capture phase
- setup for dot buttons does not seem to work, as `getChildNodes` returns empty array
- i think neither arrow nor dot controls should carry `aria-controls`, as they point to the carousel container, which isn't focusable. for further info see https://heydonworks.com/article/aria-controls-is-poop/

I can give it another round of testing next week.

**Comment by davidjerleke** [comment]
@nwidynski Thanks for your thoughtful feedback ⭐ — super helpful! I’ve updated the CodeSandbox with the following changes:

> the selector for focusable nodes should be more accurate, see [here](https://github.com/adobe/react-spectrum/blob/6c17b7c603f3fd617032f05e94a1f6815b564e35/packages/%40react-aria/utils/src/isFocusable.ts#L37)

✅ You were absolutely right — the selector needed to be more accurate.  I’ve updated it based on [the reference you shared](https://github.com/adobe/react-spectrum/blob/6c17b7c603f3fd617032f05e94a1f6815b564e35/packages/%40react-aria/utils/src/isFocusable.ts#L37)

---

> `focusin` and `focusout` events on slides should be processed in capture phase

✅ While it seemed to work without `capture: true` in my testing, I’ve added it explicitly to be safe.

---

> setup for dot buttons does not seem to work, as `getChildNodes` returns empty array

✅ Fixed! Turns out I was passing the wrong element to the plugin.

---

> i think neither arrow nor dot controls should carry `aria-controls`, as they point to the carousel container, which isn't focusable. for further info see https://heydonworks.com/article/aria-controls-is-poop/

✅ Great catch — I’ve removed `aria-controls` from arrow and dot controls, since they shouldn’t reference the non-focusable carousel container. Thanks for sharing [that article](https://heydonworks.com/article/aria-controls-is-poop/) — very useful! ✅

**Comment by nwidynski** [comment]
Glad I could be of help! One more thing that is worrying me a bit at the moment are child components implementing their own roving tabindex, as interacting with a pointer could cause them to reset the tabindex to zero.

I think it could make sense to re-apply `tabIndex=-1` on `focusout` just to make sure, but I will give it proper testing next week.

Edit: 
Additionally, there is also a problem when the accessibility plugin is used with something like the wheel gesture plugin. In this scenario focus could be on an interactive element in a canonically active slide, but then enter into an `aria-hidden` subtree because the slide is moved out of view with wheel events. 

Same applies in any scenario where rotation is performed without placing focus on a control (e.g programmatic rotation). I‘m kinda wondering what purpose `aria-hidden` still serves, since the live-region is announced via a separate element anyways.

**Comment by davidjerleke** [comment]
Hi @nwidynski, 

> Additionally, there is also a problem when the accessibility plugin is used with something like the wheel gesture plugin. In this scenario focus could be on an interactive element in a canonically active slide, but then enter into an aria-hidden subtree because the slide is moved out of view with wheel events.

It actually *shouldn’t* cause an issue in that case. There’s a safeguard in place, see [this line](https://codesandbox.io/p/sandbox/embla-carousel-loop-react-forked-49qxpg?file=%2Fsrc%2Fjs%2FAccessibility%2Fembla-carousel-accessibility.ts%3A324%2C1-324%2C79) that checks whether the slide currently contains `document.activeElement` before applying `aria-hidden`.

That means if a user has focus inside a slide (e.g. on a button or link) while a programmatic rotation happens, the plugin won’t hide that slide from the accessibility tree mid-interaction. The `aria-hidden` toggling only applies to slides that are not focused, so it shouldn’t interfere with keyboard or screen reader users staying oriented.

---

> Same applies in any scenario where rotation is performed without placing focus on a control (e.g programmatic rotation). I‘m kinda wondering what purpose aria-hidden still serves, since the live-region is announced via a separate element anyways.

I could be wrong, but as far as I understand, in a setup where announcements are handled through a separate live region, `aria-hidden` on the carousel items isn’t strictly about the announcements themselves. Its main purpose is to keep screen reader users from landing on content that isn’t “active” right now.

For example, if you have 5 slides in the DOM, all visible to assistive tech, a screen reader user could tab or swipe through every slide even though only one is visually “current.” That can be pretty confusing. `aria-hidden="true"` removes those inactive slides from the accessibility tree, so navigation is limited to the active item and the carousel controls.

**Comment by nwidynski** [comment]
> There’s a safeguard in place

Ah, i missed that one, great. Just the concern about child components remaining then 👍 

> For example, if you have 5 slides in the DOM, all visible to assistive tech, a screen reader user could tab or swipe through every slide even though only one is visually “current.” That can be pretty confusing. aria-hidden="true" removes those inactive slides from the accessibility tree, so navigation is limited to the active item and the carousel controls.

It's the roving `tabIndex` that is taking care of that though, not `aria-hidden`. I will admit however, that my knowledge ends at that point. I have no idea whether it's impacting the a11y experience to have non canonically active content visible in the accessibility tree while not tabbable. From my naive view, it seems like `aria-hidden` is rendered useless once a dedicated live region outside the carousel is being used for announcements. 

I guess its safer to keep `aria-hidden`, as long as any scenarios of focus entering into that zone can be ruled out - Maybe someone else can weigh in here?

**Comment by davidjerleke** [comment]
Hi @nwidynski,

It’s true that the **roving `tabIndex` handles keyboard (tab) navigation**, but it doesn’t stop screen readers from accessing inactive slides — that’s where `aria-hidden` comes in. When slides are removed from the accessibility tree using `aria-hidden`, my assumption is that screen readers generally **won’t be able to focus on them**, since they’re effectively hidden from assistive technology.

Separately, we **can’t prevent developers from programmatically focusing inactive slides**, but we **can discourage it in the docs**. This is unrelated to screen readers or `aria-hidden` — it’s purely about safe usage and avoiding confusion.

So my take: keep `aria-hidden` on inactive slides for accessibility, rely on roving `tabIndex` for keyboard navigation, and document that programmatic focus into hidden slides should be avoided.

**Comment by davidjerleke** [comment]
Plugin has been released, see https://www.embla-carousel.com/docs/plugins/accessibility.
