### ISSUE TITLE
Node engine?

### ISSUE THREAD

**Issue by sedlukha** [davidcetinkaya/embla-carousel#82]
Does this package really need node version in package.json? Some people use older Node.js versions. And this package works fine with them

**Comment by davidcetinkaya** [comment]
Hello Artur @sedlukha,

Thank you for noticing this.
After reading the [documentation](https://docs.npmjs.com/files/package.json#engines) again (this time more carefully), it became clear to me that I misunderstood the purpose of this field in `package.json`. Feel free to submit a PR. Otherwise I will fix this as soon as I have access to my personal computer.

Best,
David

**Comment by sedlukha** [comment]
@davidcetinkaya 

PR done. https://github.com/davidcetinkaya/embla-carousel/pull/83
Thank you for awesome package!

**Comment by davidcetinkaya** [comment]
Hello again Artur @sedlukha,
Release [v3.0.26](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v3.0.26) comes with the patch fix for this. 

Thank you for making Embla Carousel better and welcome to the [contributors club](https://github.com/davidcetinkaya/embla-carousel#contributors) 🙂.
