### ISSUE TITLE
Please consider making "overflow: hidden;" style opt-in

### ISSUE THREAD

**Issue by samhastings** [davidcetinkaya/embla-carousel#94]
Currently the [`overflow: hidden` style is hard-coded](https://github.com/davidcetinkaya/embla-carousel/blob/1c3c538751a5f617d810642ba3d439a6bb4497b4/src/react/index.ts#L50) into the React component returned by `useEmblaCarousel()`.

It would be great if this style could be documented as a recommended style in the CSS section of the installation instructions instead of being forced on the component. I'm currently working on a project where I want the inactive slides to be visible outside the container and this style is preventing this.

Happy to submit a PR if this is something you would consider accepting!

**Comment by davidcetinkaya** [comment]
Hello Sam (@samhastings),

Thank you for your question. My understanding is that most React users appreciate that this is handled automatically because it’s convenient.

With that said, I understand that this won’t be good in every use case so maybe we can discuss possible solutions before taking action?

With the current way things are done, the overflow property can be overridden by passing a `className` that applies styles to override this. I know this isn’t optimal because every project doesn’t use class names for styling and this also requires !important` which isn’t beautiful.

One suggestion that comes to my mind is to add a style property to the component which defaults to `{ overflow: “hidden” }`.

I would be happy if we could get this discussion going as soon as possible because I’m going to refactor the hook soon, and it would be nice to solve this request too.

What’s your thoughts about my suggestion? Or do you still think removing this is the best option?

Kindly
David

**Comment by samhastings** [comment]
Hi David

Thanks for your quick and in-depth response!

I think your idea of accepting a `style` prop would work, as would accepting an `overflow` prop (typed as  `'visible' | 'hidden'`) which could be passed to a `style` object in the hook. To me this seems like it would create a cleaner API but does prevent additional inline styles being specified (which may not be the end of the world as the `className` is also passed down).

The reason I was reluctant to use a `className` is that I'm using [Tailwind CSS](https://tailwindcss.com/) on this project where an `!important`flag isn't present on the `overflow-visible` class.

Sam

**Comment by davidcetinkaya** [comment]
Hello again Sam (@samhastings),

Thank you for sharing your additional thoughts. Just wanted to say that I’m looking into this. I’m considering exposing a `ref` that can be used on your own component instead of the React component `EmblaCarouselReact` which is the current implementation. This would make the Embla footprint even smaller when it comes to forcing stuff on the user.

Would this make things easier for you? Let me know if my explanation is unclear.

Best
David

**Comment by davidcetinkaya** [comment]
Hi Sam (@samhastings),

Would exposing a `ref` instead of `EmblaCarousel` component help? That would enable you to attach the ref to your own component.

Kindly
David

**Comment by samhastings** [comment]
Can I check I'm understanding you correctly? I'm assuming the code would look something like this...

```
const [emblaRef] = useEmblaCarousel({ loop: false });

return (
    <div ref={emblaRef} className='something-or-other'>
        {...}
    </div>
);
```

**Comment by davidcetinkaya** [comment]
Hello Sam (@samhastings),

Exactly like that! And the second hook variable you omitted in your example will still be the Embla API like now.

```javascript 
const [emblaRef, emblaApi] = useEmblaCarousel({ loop: false });

return (
    <div ref={emblaRef} className='something-or-other'>
        {...}
    </div>
);
```

Kindly 
David

**Comment by samhastings** [comment]
It would certainly work well for me, but wouldn't this be a BC break though? Unless you're going to introduce it in a new `useEmblaRef()` hook of course!

**Comment by davidcetinkaya** [comment]
Hello Sam (@samhastings),

Yes it is. I've been wanting to refactor the `useEmblaCarousel()` hook anyway so I just did that and released it now. Please read the [migration guide here](https://github.com/davidcetinkaya/embla-carousel/releases/tag/v4.0.0), and let me know if it solves your issue 🙂.

Best
David

**Comment by davidcetinkaya** [comment]
Hello Sam (@samhastings),

Have you had a chance to try the new version out yet?

Best
David

**Comment by davidcetinkaya** [comment]
@samhastings I'm closing this as resolved because the [ref](https://github.com/davidcetinkaya/embla-carousel/issues/94#issuecomment-680747881) implementation has been released.

**Comment by samhastings** [comment]
Hi David, sorry that it's taken me so long to get a chance to try this. The project was put on hold for a couple of weeks while I worked on other stuff. Pleased to say this is working perfectly. Thanks for taking the time to implement my request. I really appreciate it.

**Comment by davidcetinkaya** [comment]
Hello @samhastings,
I understand, we can all be busy sometimes. Thanks a lot for taking the time to confirm that it’s working as expected. Enjoy 😊.

Best
David
