### ISSUE TITLE
How about adding minification?

### ISSUE THREAD

**Issue by jeiea** [davidcetinkaya/embla-carousel#97]
Currently there seems to be no minification process. Adding it may decrease the package size.

And original source is included to the final package as well despite of source maps. It may be removed.

**Comment by davidcetinkaya** [comment]
Hi @jeiea,

Thank you for your question. In order to understand you better, I need answers to the following questions, so please take a moment to answer them:

- Are you using the vanilla-js or React.js version of Embla Carousel?
- Are you using any module bundler like Webpack or a script tag to integrate Embla Carousel?

Kindly 
David

**Comment by jeiea** [comment]
1. React
2. webpack

**Comment by davidcetinkaya** [comment]
@jeiea, I might be misunderstanding you, but if you’re using a module bundler, that should take care of the minification process. Meaning your Webpack setup should minify all your JavaScript when creating your final production ready bundle. 

I think this is a convention for ESM modules and Common JS modules in NPM packages. Only files intended for CDN usage and script tags should be minified. This is my understanding of how it should work.

Best
David

**Comment by jeiea** [comment]
I agree you are right. 

> And original source is included to the final package as well despite of source maps. It may be removed.

I misread type information files. There was no problem.

**Comment by davidcetinkaya** [comment]
@jeiea ah, I see 🙂.

Thank you and enjoy!
David
