### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by Grawl** [davidcetinkaya/embla-carousel#98]
Feature request

**Comment by davidcetinkaya** [comment]
Hello @Grawl,

Thank you for your feature request. Embla Carousel is a **bare bones** carousel library so I'm not sure it makes sense to implement this into the package core, because it will increase the bundle size for all users.

With that said, would you want me to create a **CodeSandbox** demonstrating how to achieve this for you?

Kindly,
David

**Comment by davidcetinkaya** [comment]
Closing this due to lack of response.

**Comment by solerfranco** [comment]
Did you by any chance ended up doing a plugin or a CodeSandbox that shows this feature?

**Comment by davidjerleke** [comment]
@solerfranco at the time of writing no, there’s no fullscreen plugin.

**Comment by romatou** [comment]
> With that said, would you want me to create a **CodeSandbox** demonstrating how to achieve this for you?

Would be great if you could provide a demo for fullscreen slider, @davidjerleke. I'm stuck with recalculating image sizes and my slider stops between images in full-screen mode.
